### ISSUE TITLE
请问批量下载文件如何使用呢？比如同时去下载几十个文件的场景

### ISSUE THREAD

**Issue by HolenZhou** [liangjingkanji/Net#10]
如题.
想一次发起几十个文件的下载请求，并可以获取到总体的下载进度，该如何coding呢？
现在在项目中使用的是OKDownload，但是写起来过于复杂，想通过协程实现，不知这个库是否可以

**Comment by liangjingkanji** [comment]
暂时不支持, 3.0将支持更完善的下载功能

**Comment by HolenZhou** [comment]
谢谢答复，期待！！
