### ISSUE TITLE
从Sample 节流阀的bug引发的疑问。

### ISSUE THREAD

**Issue by the6nnoo** [liangjingkanji/Net#102]
net/src/main/java/com/drake/net/utils/FlowUtils.kt 的109行，我看到提交日志里以前是s.toString() ,但是在某个版本改成了s。
如果用s这个对象的话,distinctUntilChanged()是一直拒绝的。望改正

**Comment by liangjingkanji** [comment]
你看[EditDebounceFragment](https://github.com/liangjingkanji/Net/blob/188f4e2b314c22b5f8031d382ce3c11e4b2658b7/sample/src/main/java/com/drake/net/sample/ui/fragment/EditDebounceFragment.kt#L15)也使用`distinctUntilChanged`并没有任何问题

我删掉`toString`主要是因为s可能为富文本内容

**Comment by liangjingkanji** [comment]
我可能理解错了你的意思, 你的意思应该是`distinctUntilChanged`没有实现去重吧

**Comment by the6nnoo** [comment]
distinctUntilChanged 会一直拦截数据 导致这里走不到后面的步骤。
因为对于flow 而言 Editable这个对象一直没变

**Comment by liangjingkanji** [comment]
的确, 忘记输入框持有单个对象了

既然问题是你发现的你发起pr修复? 如果你没空我可以代劳

**Comment by the6nnoo** [comment]
本来想改的，看到这里之前被去掉了，就来问问

**Comment by liangjingkanji** [comment]
我的严重疏漏, 你改完我就发个版
