### ISSUE TITLE
强哥，我碰到一个神奇的问题，不知道如何排查了

### ISSUE THREAD

**Issue by BatterMan-Li** [liangjingkanji/Net#105]
目前我的参数和链接都是一样的，使用postman能请求通过
![image](https://user-images.githubusercontent.com/28614345/178934319-224676f6-0da8-4978-b0c3-b58afd80b1ad.png)
![image](https://user-images.githubusercontent.com/28614345/178934391-004f5c2d-2888-4abc-9c13-5d472b896cf3.png)

**Comment by BatterMan-Li** [comment]
![image](https://user-images.githubusercontent.com/28614345/178935598-17ba45fa-5300-4331-a64e-60e1587d2b59.png)

**Comment by liangjingkanji** [comment]
400 属于服务器自定义的错误, 具体原因应该问后端开发

以下步骤排查
1. 校验是否存在多余参数
2. 是否非同一网络
3. 尝试使用okHttp原始请求api

**Comment by BatterMan-Li** [comment]
问题排查出来了，请求会有延时，会根据订单的状态来处理的
