### ISSUE TITLE
post请求时想同时传递param也要传输body

### ISSUE THREAD

**Issue by boboqun** [liangjingkanji/Net#107]
## 问题描述
post请求时想同时传递param （接口文档里叫query，虽然看起来像get请求才是用的）
也要传输body

我进行了尝试，如果添加上body后(json那部分)，param就会失效。如果不写json，param就能正常发出
```kotlin
    Post<CheckInResp>("/punchIn/userPunchIn") {
                    param("lngLat", stringBuilder.toString())
                    param("uuid", checkInStatus.punchInRule.uuid)
                    param("isUpdate", false)
                    json(
                        "xxx" to xxxx,
                    )
                }
```

### 期望行为

期望能够param和body均能发出。或者，教育一下我该怎么做是最正确的，我去和后端对线。

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net: 3.4.10
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
1. param(表单)和json都属于body, 无法共存
2. query参数请使用`setQuery`, Get请求下setQuery才等效于param

**Comment by boboqun** [comment]
ok 搞定 感谢大佬
