### ISSUE TITLE
怎么改用 JsonBody呀？

### ISSUE THREAD

**Issue by listenwinding** [liangjingkanji/Net#11]
怎么改用 JsonBody呀？

**Comment by listenwinding** [comment]
需要自定义BodyRequest 是吗？

**Comment by spysoos** [comment]
同问

**Comment by liangjingkanji** [comment]
可以请求依然使用表单，然后在拦截器中取出数据拼成body。 或者在Post后面的大括号里直接使用body()函数传入JsonBody对象

**Comment by Xiao1209** [comment]
的确，这是一种办法。
提议，是否可以使用更简便的方式来进行Json传参呢？毕竟这是一个常用上传方式。
```kotlin
Post<String>(url){
  json{
    param(key,value)
  }
}
```

**Comment by liangjingkanji** [comment]
@Xiao1209 如果只是简单的简直对那拦截器处理更方便，如果是嵌套json你这种写法也局限了

**Comment by liangjingkanji** [comment]
> 的确，这是一种办法。
> 提议，是否可以使用更简便的方式来进行Json传参呢？毕竟这是一个常用上传方式。
> 
> ```kotlin
> Post<String>(url){
>   json{
>     param(key,value)
>   }
> }
> ```

而且JSON可能存在一个固定参数

**Comment by liangjingkanji** [comment]
> 的确，这是一种办法。
> 提议，是否可以使用更简便的方式来进行Json传参呢？毕竟这是一个常用上传方式。
> 
> ```kotlin
> Post<String>(url){
>   json{
>     param(key,value)
>   }
> }
> ```

你看下新的Demo这样请求方式如何

![image](https://user-images.githubusercontent.com/21078112/113705887-93ceb300-9710-11eb-9524-6bb61b1b7cc5.png)


[JSON请求](https://github.com/liangjingkanji/Net/blob/master/sample/src/main/java/com/drake/net/sample/ui/fragment/RequestMethodFragment.kt)
