### ISSUE TITLE
指定泛型为Model情况下缓存无法读取

### ISSUE THREAD

**Issue by tanranran** [liangjingkanji/Net#110]
## 问题描述
指定泛型为Model情况下缓存无法读取，原因是缓存模式下，response.request.kType 读取为空
### 期望行为
指定泛型为Model情况下缓存可以读取
## 如何复现
将Net 项目中sample的PreviewCacheFragment 请求代码改为下面的代码
```java
        scopeNetLife {
            // 然后执行这里(网络请求)
            binding.tvFragment.text = Get<List<HomeBannerModel>>("banner/json") {
                setCacheMode(CacheMode.WRITE)
            }.await().toString()
            Log.d("日志", "网络请求")
        }.preview(true) {
            // 先执行这里(仅读缓存), 任何异常都视为读取缓存失败
            binding.tvFragment.text = Get<List<HomeBannerModel>>("banner/json") {
                setCacheMode(CacheMode.READ)
            }.await().toString()
            Log.d("日志", "读取缓存")
        }
```

## 版本
- Net:3.4.12
- OkHttp: 4.10.0
- Android: 31
- Gradle:  4.1.0
- Android Studio: Android Studio Chipmunk | 2021.2.1 Patch 1

**Comment by liangjingkanji** [comment]
能fork仓库复现问题吗?

**Comment by tanranran** [comment]
@liangjingkanji 已fork https://github.com/tanranran/Net，有问题的位置在PreviewCacheFragment中

**Comment by liangjingkanji** [comment]
好的

**Comment by cipchk** [comment]
@liangjingkanji 类似问题，不过我的是缓存序列化时 `response.request.kType` 为 `null` 值；有什么解决办法吗？

**Comment by liangjingkanji** [comment]
已修复请使用最新版本
