### ISSUE TITLE
请求返回体是mp3音频流怎么搞

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Net#113]

**Comment by liangjingkanji** [comment]
返回体都是Response, 具体看你怎么解析

mp3你可以使用File接受

**Comment by SaltedFish-Extreme** [comment]
> 返回体都是Response, 具体看你怎么解析, 比如字节流或字符串或文件
> 
> mp3你可以使用File接受

我是用File接收的，但是好像没保存下来，我都不知道请求成没成功😂但是也没有报错，没走runcatch，吐司能弹出来保存的位置，但是那个文件夹里面又没有😓老哥能给个伪代码，我看看怎么把mp3音频流保存成mp3文件吗😥

**Comment by liangjingkanji** [comment]
File对象你都不知道怎么判断是否文件存在吗? 

```kotlin
val file = Get<File>("/path").await()
file.exists() // 判断文件是否存在
```

**Comment by SaltedFish-Extreme** [comment]
> ```kotlin
> val file = Get<File>("/path").await()
> file.exists() // 判断文件是否存在
> ```

对，我是这么做的，就因为判断为真，我才进行文件播放的，但是那个文件夹里并没有这个mp3文件，很奇怪😂执行播放就报错了😥

**Comment by SaltedFish-Extreme** [comment]
唉，明天我再捣鼓捣鼓吧，打扰老哥了😢

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 强东哥，这个返回的是个音频流字符串，我是真不知道该怎么保存成mp3文件了😂能帮帮我吗😥
![image](https://user-images.githubusercontent.com/54784104/181671543-8ec3bf8a-5425-4544-b706-f2b8babcb042.png)
![image](https://user-images.githubusercontent.com/54784104/181671693-55159b3c-17cb-4a92-bb34-2c0fd3350cea.png)

**Comment by liangjingkanji** [comment]
这个和本框架无关, 你可以去问问其他相关的同行

**Comment by SaltedFish-Extreme** [comment]
> 这个和本框架无关, 你可以去问问其他相关的同行, 具体我也不清楚

好吧😥

**Comment by SaltedFish-Extreme** [comment]
研究了一上午，最后通过打印File的内容发现请求出错了，最后发现是我post请求参数写法错了，应该是用param包装，我直接用to拼接的😓最后通过File把文件保存成mp3格式的没问题了😂
