### ISSUE TITLE
scopeDialog(Dialog()) 提个建议

### ISSUE THREAD

**Issue by sdjwj1118** [liangjingkanji/Net#114]
### 期望行为
在使用scopeDialog(Dialog())时能不能提供一个延时值，现在请求dialog弹窗都是一闪就没了 产品觉得用户体验稍差 是否能够增加这样的值设定让dialog显示和关闭的时候让用户体验好一些
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
支持创建全局/单例Dialog, 你可以自己在自定义的Dialog里面进行延迟处理

产品不专业, 建议开除, 网速快关闭是很正常的事情, 鸡蛋里挑骨头是无意义的行为
苹果公司很多页面都没有甚至都没有设计缺省页, 你们还在纠结于网速太快一闪而过, 那是不是系统吐司还得弄个显示动画. 
学会拒绝不合理需求才是一个成熟的开发者
人人都是产品经理, 总有连系统交互都不懂的人指手画脚

**Comment by Chen-Xi-g** [comment]
> 支持创建/创建自己的对话框，你可以在里面自定义的对话框进行延迟处理
> 
> 产品不专业，建议开除 网速快关闭是很正常的事情，学会接受不适合作为成熟的开发者

我就喜欢你这个性格，建议开除+1.
