### ISSUE TITLE
转换器内若返回一个 `null` 值时会产生 `NullPointerException` 异常

### ISSUE THREAD

**Issue by cipchk** [liangjingkanji/Net#115]
## 问题描述

```kotlin
class DemoConverter : NetConverter {
    override fun <R> onConvert(succeed: Type, response: Response): R? {
        return null
    }
}
```

最后，会在全局的异常捕获内收到一个 `com.drake.net.exception.ConvertException` 异常，但是转换后返回一个 `null` 值理应是合理的需求。

**Comment by liangjingkanji** [comment]
请求动作指定泛型为`可空类型`才允许在转换器返回Null

```kotlin
Post<Model?>("/path").await() // 这时允许转换器返回null
```

在Kotlin中非可空类型不允许接受Null值

**Comment by liangjingkanji** [comment]
在文档第三行有提到转换器返回Null的处理: [使用转换器](https://liangjingkanji.github.io/Net/converter/)
