### ISSUE TITLE
缓存疑惑

### ISSUE THREAD

**Issue by cipchk** [liangjingkanji/Net#117]
**前置条件**

1、配置 `cache(Cache(cacheDir, 1024 * 1024 * 128))` 
2、`Get` 时不做任何与缓存相关，例如： `setCacheMode` 或 `setCacheControl`，HTTP 也无返回 `Cache-Control`

那么：

1、第二次请求后，`cacheResponse` 与 `networkResponse` 同时都有值，那么此时算是真实请求，还是来自缓存？
2、如何准确的判断是从缓存中数据？

**Comment by liangjingkanji** [comment]
`cacheResponse`有值就算来自缓存, okHttp也是如此设计

**Comment by liangjingkanji** [comment]
你说的前置条件, 你去缓存目录看下是否存在缓存文件

**Comment by cipchk** [comment]
单纯使用 `cacheResponse ` 来判断并不是最准确的，还是需要依据情况判断，见 [这一段落](https://stackoverflow.com/a/41729479/14027531) 符合我判断期望的结果与我实际是否发起请求一致。

**Comment by liangjingkanji** [comment]
我看你发的内容提及也是cacheResponse不为null则来自缓存, 我理解有误吗?
