### ISSUE TITLE
关于单个拦截器的加入

### ISSUE THREAD

**Issue by shaycormac** [liangjingkanji/Net#12]
如题，项目中刚开始登录的时候，在请求头是不需要带有token的，登录完后拿到token，后面的请求都要在这次请求头上加入这个token,像这种情况有什么比较好的解决方案，因为在sample中看到提示拦截器仅仅支持整个项目，谢谢。

**Comment by liangjingkanji** [comment]
判断token是否存在，存在才添加，登陆才存在tiken

**Comment by shaycormac** [comment]
> 判断token是否存在，存在才添加，登陆才存在tiken

嗯，我在看你的文档，还可以在拦截器中使用标签来控制，因为业务上就刚登录的两三个接口不要token，但是需要加其它一些请求头，谢谢你。
