### ISSUE TITLE
后台需求的奇葩Get请求，Required request body is missing

### ISSUE THREAD

**Issue by TianGuisen** [liangjingkanji/Net#120]
get请求中带有json类型的body。
会报错
{"statusCode":500,"message":"Required request body is missing: public com.kemai.bigdata.ops.data.common.RYTM<?> com.kemai.bigdata.ops.data.controller.YunTiaoMaController.md5ForCQuery(com.kemai.bigdata.ops.data.model.YunTiaoMaRequestContext)","size":0}

Net.INSTANCE.get(url, null, new Function1<UrlRequest, kotlin.Unit>() {
            @Override
            public kotlin.Unit invoke(UrlRequest urlRequest) {
                urlRequest.param("barcode",Barcode);
                urlRequest.param("hashCode",barcodeEncrypt(Barcode));
                return null;
            }
        }).enqueue(new Callback() {
            @Override
            public void onFailure(@NonNull Call call, @NonNull IOException e) {
        
            }
    
            @Override
            public void onResponse(@NonNull Call call, @NonNull Response response) throws IOException {
        
            }
        });

如何实现像下面apipost中的请求。
![image](https://user-images.githubusercontent.com/19662707/182788107-2a6e35ac-750e-4aa2-a3b7-79748e1833a0.png)

**Comment by liangjingkanji** [comment]
OkHttp框架不支持, 所以Net也不支持
