### ISSUE TITLE
下载网易云音乐失败

### ISSUE THREAD

**Issue by geziin** [liangjingkanji/Net#124]
作者大大你好，我用Net框架下载网易云音乐，只能下载62b就回调成功了，一直找不到问题出在哪，作者可以帮我看下吗，谢谢了，测试链接
http://music.163.com/song/media/outer/url?id=1958150862

下图是我的代码配置和下载文件大小情况
![image](https://user-images.githubusercontent.com/88422082/186635102-33d9d478-2280-4bc9-a104-2bf2835114ab.png)
![86c45d298cbbdfe1a54414477e204e2](https://user-images.githubusercontent.com/88422082/186635252-bbd58bec-d73e-4f72-932f-71739b72a387.jpg)

**Comment by liangjingkanji** [comment]
你这是正确的下载地址吗? 你自己用浏览器或者其他工具试下, 我测试不能下载会重定向到404页面

**Comment by geziin** [comment]
用浏览器可正常下载，而且我在项目里可以正常播放音乐
![image](https://user-images.githubusercontent.com/88422082/186636249-53433dbb-74d5-45c2-90ae-24d80129e5d8.png)

**Comment by liangjingkanji** [comment]
Net使用的是OkHttp作为Http请求层, 如果你还有问题可以使用原始OKHttp的Api去请求该地址, 或者Postman等工具

**Comment by geziin** [comment]
我好像知道怎么回事了，需要拿到我那个链接再请求一次接口才能得到真正的下载链接，谢谢作者大大解惑
