### ISSUE TITLE
我们交流群被和谐了，有个问题请教一下大佬

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/Net#125]
关于序列化问题，这个我有点不太明白
![W3 ~9O2AB9P3C2 V18JUSJ1](https://user-images.githubusercontent.com/18433246/187645183-2798367d-c030-433d-adc7-d9723ac16d15.png)

**Comment by zkzk7749** [comment]
我这个集合我准备搞成BRV的多类型，所以这里只能搞一个ANY

**Comment by liangjingkanji** [comment]
这是语法基础
Any是无法被序列化的(序列化框架不知道如何解析), 你参考多类型的demo
数据不要求是Any类型, 只是BindingAdapter.models是`List<Any>`代表可以接受任何类型集合, List<Model>同样可以赋值

请阅读README有群号, 即使被和谐也会有新的
