### ISSUE TITLE
如果要配置多个域名怎么处理？

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/Net#130]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
使用什么域名就传入什么域名, 参照文档[多域名](https://liangjingkanji.github.io/Net/config/#_4)

**Comment by lastzhou** [comment]
ok,非常强大
