### ISSUE TITLE
关于转换器

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/Net#131]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

![图片](https://user-images.githubusercontent.com/28262649/191430827-4ebe6c13-abbb-4461-9eb7-dc1c0174ee27.png)

这块逻辑为什么是写在catch里面？
异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
你不想catch也行随你, 这么简单的代码逻辑我不想多讲
因为默认处理器无法处理(抛出异常)才交由自定义处理, 我建议你看下try里面为什么抛出异常, 而不是为什么写到catch

**Comment by lastzhou** [comment]
![图片](https://user-images.githubusercontent.com/28262649/191433979-c9aeada4-214c-4ebc-a8db-98523139be10.png)

已看懂，解析失败，就会丢出一个response

**Comment by liangjingkanji** [comment]
是的, 对于默认转换器不支持的类型就会抛出异常
