### ISSUE TITLE
解析出错

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/Net#132]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图
![图片](https://user-images.githubusercontent.com/28262649/191451177-d5520e15-2f77-473a-a7a0-141b3a12b9b3.png)

定义了实体类，怎么还是找不到

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
解析JSON无关乎本框架, 这个实体类你可能没有用注解`@Serializable`修饰

**Comment by lastzhou** [comment]
用了，我直接复制过来的

**Comment by liangjingkanji** [comment]
那就应该是没有为ks添加kapt插件

**Comment by lastzhou** [comment]
好的，我再试一下

**Comment by lastzhou** [comment]
![图片](https://user-images.githubusercontent.com/28262649/191693662-7f4a73f8-de89-478d-bfa3-2e24fd0c91a8.png)

我用的as 最新版,  这个插件一编译就报错

**Comment by liangjingkanji** [comment]
```groovy
id 'org.jetbrains.kotlin.kapt'
```
具体你搜下怎么添加kapt吧...

**Comment by lastzhou** [comment]
我写法有问题，找到原因了
