### ISSUE TITLE
Kotlin版本兼容问题

### ISSUE THREAD

**Issue by Chen-Xi-g** [liangjingkanji/Net#133]
## 问题描述
```
Class 'com.drake.net.NetConfig' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from 
```
版本从3.4.6升级到3.5.1时提示Kotlin版本兼容异常，无法正常使用。

### 期望行为
正常编译

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net: 3.5.1
- OkHttp:  4.9.1
- Android:  31
- Gradle:  gradle-6.5-bin
- Android Studio:  2021.2.1

**Comment by liangjingkanji** [comment]
建议升级kotlin插件版本

**Comment by Chen-Xi-g** [comment]
已经是最新的插件了
![image](https://user-images.githubusercontent.com/37918545/192668603-fd2f61cc-c643-4edd-bf06-8b69bbc69661.png)

**Comment by liangjingkanji** [comment]
能在femo复现问题吗?

**Comment by Chen-Xi-g** [comment]
https://github.com/Chen-Xi-g/NetDemo
这个链接是我新创建的空项目，空项目中仅引入依赖，无任何其他操作，错误信息在images中

**Comment by liangjingkanji** [comment]
你光升级插件不提高项目的kt版本有什么用?
```groovy
ext.kotlin_version = "1.5.30"
```

**Comment by Chen-Xi-g** [comment]
低版本Kotlin不兼容？

**Comment by liangjingkanji** [comment]
版本相差过大可能kt插件不兼容, 这种问题尝试下就好了, 毕竟kt插件不是我写的, 升级kt插件也不存在不兼容问题
