### ISSUE TITLE
File.install方法被删除

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/Net#134]
3.5.0版本删除了
File.install。
我觉得这个方法很好用的，能不能再次拿出来用啊，如果可以的话我就复制出来用了啊

**Comment by liangjingkanji** [comment]
更新记录里面提到了是为了删除安装权限, 因为谷歌商店认为普通应用不应当有安装应用权限
```
删除权限REQUEST_INSTALL_PACKAGES(谷歌商店权限要求)
```

关于安装App功能建议使用[Engine](https://github.com/liangjingkanji/Engine)库中的`AppUtils.installApp`方法, 并且自己添加安装权限

**Comment by liangjingkanji** [comment]
当然你复制出Net以前的`install()`代码实现也是完全可以的

**Comment by zkzk7749** [comment]
感谢东哥百忙之中回复啊，小弟跪谢了
