### ISSUE TITLE
阿里云oss的MD5校验无法通过问题

### ISSUE THREAD

**Issue by pangwanchun** [liangjingkanji/Net#135]
阿里云oss的Content-MD5字段使用base64编码，本项目使用hex编码，无法通过校验，希望提供base64编码的md5校验。

**Comment by liangjingkanji** [comment]
`Response.file`中使用到`Content-MD5`来匹配是否为相同文件, 但是并没有使用任何编码处理
```kotlin
// ...
if (request.downloadMd5Verify()) {
    val md5Header = request.header("Content-MD5") // 直接取出值来判断
    if (file.md5() == md5Header) return file
}
```

另外你需要任何特殊处理的可以在转换器里面自己判断然后返回File对象

**Comment by pangwanchun** [comment]
> `Response.file`中使用到`Content-MD5`来匹配是否为相同文件, 但是并没有使用任何编码处理
> 
> ```kotlin
> // ...
> if (request.downloadMd5Verify()) {
>     val md5Header = request.header("Content-MD5") // 直接取出值来判断
>     if (file.md5() == md5Header) return file
> }
> ```
> 
> 另外你需要任何特殊处理的可以在转换器里面自己判断然后返回File对象

![image](https://user-images.githubusercontent.com/10494764/196124978-6b672f1b-97ab-48e9-8ef0-15298bd8eb16.png)

谢谢，我的意思是获取文件md5的byte数组后阿里云oss是通过base64转字符串的，而且本项目是通过hex转字符串的，目前的想法是用拦截器改调阿里云返回的Content-MD5

**Comment by liangjingkanji** [comment]
md5值就是如此, 这是阿里云的问题

其实我更建议在转换器里面处理

将以下代码放到转换器里面合适位置即可, `response.file也只是转换器里面一个框架封装的函数而已`
```kotlin
if (request.downloadMd5Verify()) {
    val md5Header = Base64Utils.decode(request.header("Content-MD5")) // 取出值解码base64来判断
    if (file.md5() == md5Header) return file
}
```

**Comment by pangwanchun** [comment]
好的，还是请你修复吧，我还没提过pr
![image](https://user-images.githubusercontent.com/10494764/196158902-bac261db-f18a-4b45-be81-baa12ca4eb2b.png)
还有个问题也麻烦一起修复下，这里用request应该不对吧，request里是拿不到Content-MD5的，我改成从response就行了

**Comment by liangjingkanji** [comment]
我一并修复了, 请使用以下依赖看是否解决问题
```
implementation 'com.github.liangjingkanji:Net:d54535ff14'
```

**Comment by liangjingkanji** [comment]
如果是对的, 解码base64应该也是匹配的, 你能确定问题所在吗?

**Comment by liangjingkanji** [comment]
`file.md5()`这个函数不能改变(因为返回值必须是md5值), 只能在调用的时候进行base64编码

**Comment by pangwanchun** [comment]
> `file.md5()`这个函数不能改变(因为返回值必须是md5值), 只能在调用的时候进行base64编码

但是原始的md5是个字节数组，阿里云oss把这个字节数组用base64编码了，本项目是用hex编码了，我查了下hex编码也叫base16，两边算出来的原始md5应该一样的，后续用了不同的编码转字符串才不匹配

**Comment by pangwanchun** [comment]
> > 我一并修复了, 请使用以下依赖看是否解决问题, [如何加入开源项目](https://liangjingkanji.github.io/document/)
> > ```
> > implementation 'com.github.liangjingkanji:Net:d54535ff14'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 没有问题后我会发布正式版本
> 
> 我试了下问题还在，既然Content-MD5返回的是正确的，修改file.md5()生成base64编码的md5就行了 ![image](https://user-images.githubusercontent.com/10494764/196181534-d7fd4871-73aa-44cf-8b07-7b92793e4b92.png) ![image](https://user-images.githubusercontent.com/10494764/196181643-d8086e2a-2586-463b-8e3f-88e5d890ba9f.png)

我这里也不对要用Base64.NO_WRAP
![image](https://user-images.githubusercontent.com/10494764/196187363-9df64c91-65a7-463c-b13b-46b6467330ed.png)

**Comment by liangjingkanji** [comment]
试下最新版本
```
implementation 'com.github.liangjingkanji:Net:d54535ff14'
```

**Comment by liangjingkanji** [comment]
试下dev依赖版本, 已经修复MD5校验问题, 并且检查修复了下流未关闭问题
```
implementation 'com.github.liangjingkanji:Net:6a45b6345f'
```
