### ISSUE TITLE
请求回调问题

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/Net#137]
## 问题描述
![图片](https://user-images.githubusercontent.com/28262649/199140809-9dfce95f-dcab-4c01-9d9b-0e652ad99f3d.png)
这里可以支持泛型参数，解析？

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
当然可以支持，不过需要你自己实现，因为这是OkHttp的接口回调，过于麻烦我一般不推荐使用

**Comment by liangjingkanji** [comment]
有协程你不用你用最原始的回调请求，这会导致一系列功能都无效

**Comment by lastzhou** [comment]
![图片](https://user-images.githubusercontent.com/28262649/199142941-d6da4b5f-6efb-4fc4-addd-9b07d2ede5e6.png)
如果服务器报错了，这里也会返回？

**Comment by liangjingkanji** [comment]
会抛出异常，你看下文档吧，或者demo试下

**Comment by lastzhou** [comment]
抛出异常，不太优雅，我看其他人也都是这么做的

**Comment by liangjingkanji** [comment]
协程都是这么处理的，这就是最优雅的处理方式，回调请求就是最差的处理方式

**Comment by liangjingkanji** [comment]
我觉得你根本没有理解什么叫做异常处理机制，你还停留在成功回调错误回调的思维上，而且你根本没看文档里面对错误处理

**Comment by lastzhou** [comment]
嗯，我先看下文档，研究下

**Comment by liangjingkanji** [comment]
不要企图通过一句一句提问来学习框架，而是通过文档和demo, 也不要有回调请求思想，Net是将异步代码同步写法的协程异步任务处理框架，并且兼容其他第三方协程框架或者操作
