### ISSUE TITLE
scopeNetLife 回调耗时

### ISSUE THREAD

**Issue by tanranran** [liangjingkanji/Net#138]
## 问题描述
scopeNetLife 回调耗时,华为mate10 机器回调大约200ms
### 期望行为
scopeNetLife 回调时间低于50ms
## 如何复现
```kotlin
val starTime=System.currentTimeMillis()
scopeNetLife {
    println("耗时："+(System.currentTimeMillis()-starTime))
}
//logcat输出 耗时：248
```
## 截图
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/5227840/199544075-c727e9a9-ff38-44e1-bbcd-3fe6e8c8fdf3.png">

## 版本
- Net:3.5.2
- OkHttp: 4.10.0
- Android:10
- Gradle: 7.2
- Android Studio:Android Studio Chipmunk 2021.2.1 Patch1

**Comment by liangjingkanji** [comment]
Duplicate of #139
