### ISSUE TITLE
读取缓存耗时

### ISSUE THREAD

**Issue by tanranran** [liangjingkanji/Net#139]
## 问题描述
读取缓存耗时,华为mate10 机器，大约180ms
### 期望行为
读取缓存耗时控制在50ms之内
## 如何复现

```kotlin
var starTime = System.currentTimeMillis()
scopeNetLife {
    Log.d("日志", "scopeNetLife耗时" + (System.currentTimeMillis() - starTime))
    starTime = System.currentTimeMillis()
    Get<String>(Api.BANNER) {
        setCacheKey(Api.BANNER)
        setCacheMode(CacheMode.READ)
    }.await().toString()
    Log.d("日志", "读取缓存耗时" + (System.currentTimeMillis() - starTime))
}
```

## 截图
<img width="907" alt="image" src="https://user-images.githubusercontent.com/5227840/199553140-87a0da2d-e281-4c59-be43-d5dd238b039c.png">

## 版本
- Net:3.5.2
- OkHttp: 4.10.0
- Android:10
- Gradle: 7.2
- Android Studio:Android Studio Chipmunk 2021.2.1 Patch1

**Comment by liangjingkanji** [comment]
1. Net采用的缓存机制是`DiskLruCache`, 这是OkHttp使用Okio实现的缓存机制, 
OKio已经是业界速度公认效率最高之一(比java.io/java.nio), 且Net所有IO相关操作全部使用的`OKio`

2. scopeNetLife使用的协程调度器切换, 这个在Net中我认为没有进一步优化空间

首先第一次执行`scope()`/IO读写都会构建线程池等初始化相对较慢, 缓存读写速度和设备性能/缓存大小有关, 你的华为Mate10速度慢很正常, 不仅是设备老久还CPU性能低下

以下是我运行结果

第一次
```
12:40:08.010  D  scopeNetLife耗时13
12:40:08.155  D  读取缓存耗时145
12:40:11.843  D  scopeNetLife耗时5
12:40:11.860  D  读取缓存耗时17
12:40:15.422  D  scopeNetLife耗时6
12:40:15.437  D  读取缓存耗时15
12:40:17.835  D  scopeNetLife耗时6
12:40:17.859  D  读取缓存耗时24
```

第二次

```
12:40:48.156  D  scopeNetLife耗时29
12:40:48.288  D  读取缓存耗时132
12:40:50.761  D  scopeNetLife耗时1
12:40:50.786  D  读取缓存耗时24
12:40:52.434  D  scopeNetLife耗时3
12:40:52.456  D  读取缓存耗时22
12:40:53.745  D  scopeNetLife耗时4
12:40:53.763  D  读取缓存耗时18
```

**Comment by tanranran** [comment]
谢谢大佬解答，我这边在充分测试验证下
