### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by LGghost** [liangjingkanji/Net#14]
在简析数据时我希望返回数据中的有一个公共的提取出来(如成功失败状态，及失败消息等)，然后通过泛行连接下面的data数据，类似于xxx<xxx>,不需要写在一起，但现在使用这种方法报“解析数据时发生异常”，我该怎么处理，希望能得到您的帮助，QQ：1424599591

**Comment by LGghost** [comment]
类似于xxx<xxx>

**Comment by liangjingkanji** [comment]
最好提供异常的堆栈信息

**Comment by liangjingkanji** [comment]
已解决
