### ISSUE TITLE
请问怎么获取重定向的地址

### ISSUE THREAD

**Issue by qq570026938** [liangjingkanji/Net#140]
## 问题描述
部分地址存在302重定向，但是请求框架获取到的code是200，在网页上请求是302地址，请问怎么获取重定向后的地址
### 期望行为
获取重定向地址

**Comment by liangjingkanji** [comment]
Net和Retrofit一样使用OkHttp作为Http协议层. 支持OkHttp生态
OkHttp会自动根据302重定向到指定URL, 你搜索下`OkHttp重定向处理`

**Comment by qq570026938** [comment]
> Net和Retrofit一样使用OkHttp作为Http协议层. 支持OkHttp生态 OkHttp会自动根据302重定向到指定URL, 你搜索下`OkHttp重定向处理`

好的，这个库不能直接获取重定向地址对吧，我得自己处理一下获取重定向地址才行

**Comment by liangjingkanji** [comment]
你获取重定向URL做什么? OkHttp和浏览器一样会自动跳转到重定向指定的URL

**Comment by liangjingkanji** [comment]
> > Net和Retrofit一样使用OkHttp作为Http协议层. 支持OkHttp生态 OkHttp会自动根据302重定向到指定URL, 你搜索下`OkHttp重定向处理`
> 
> 好的，这个库不能直接获取重定向地址对吧，我得自己处理一下获取重定向地址才行

这个库支持OkHttp拦截器, 拦截器支持获取重定向URL

**Comment by qq570026938** [comment]
好的，明白了，我需要拿到重定向的地址，手动做后续的处理
