### ISSUE TITLE
post 表单提交报错

### ISSUE THREAD

**Issue by lastzhou** [liangjingkanji/Net#143]
## 问题描述
![图片](https://user-images.githubusercontent.com/28262649/202667868-06a6e115-122d-4d52-abf1-fa740afea332.png)

这种表单参数的请求，Net 中不需要处理？ 

![图片](https://user-images.githubusercontent.com/28262649/202668186-7bc37033-4966-474b-bf4f-4c2c74fa863f.png)
我拿过来写，报错了

![图片](https://user-images.githubusercontent.com/28262649/202668586-5e74e19a-c82d-4e18-941d-cdc2f699571a.png)

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
你明白`@FormUrLEncoded`是什么含义吗? Net对于参数部分是基于最简单的OkHttp封装可以稍微点进去看下

`param()`中参数`encoded = true`即等于retrofit修饰注解`@FormUrLEncoded`

**Comment by lastzhou** [comment]
不知大佬框架还有这么个参数，文档里面也没说，
![图片](https://user-images.githubusercontent.com/28262649/202947307-96f9202f-7613-42ba-96b3-884c012dc604.png)


看了源码才知道啊，涨姿势了

**Comment by liangjingkanji** [comment]
文档不会介绍函数重载的每个参数, 只会介绍方法名, 你调用的时候IDE会提示参数的
