### ISSUE TITLE
com.github.liangjingkanji:BRV

### ISSUE THREAD

**Issue by aaaking** [liangjingkanji/Net#144]
com.github.liangjingkanji:BRV 是啥东东？

**Comment by liangjingkanji** [comment]
https://github.com/liangjingkanji/BRV

**Comment by aaaking** [comment]
> https://github.com/liangjingkanji/BRV

嗯。 看到了，多谢

**Comment by liangjingkanji** [comment]
那你可能还没看到[spannable](https://github.com/liangjingkanji/spannable)
