### ISSUE TITLE
怎么获取响应头体

### ISSUE THREAD

**Issue by artillerymans** [liangjingkanji/Net#145]
## 问题描述
因为请求后返回回来的信息中它的Url有变化，我想获取它的响应体里面的所有信息

### 期望行为
这个我应该怎么做？

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
```kotlin
scopeNetLife{

}
```

**Comment by artillerymans** [comment]
感谢
