### ISSUE TITLE
为何用东子照片

### ISSUE THREAD

**Issue by GongShengyue** [liangjingkanji/Net#146]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
我头像不是东子
