### ISSUE TITLE
下载报权限异常

### ISSUE THREAD

**Issue by artillerymans** [liangjingkanji/Net#148]
## 问题描述
![image](https://user-images.githubusercontent.com/16060581/204182758-b0e65837-e643-4fdc-99c3-989a21451adf.png)

Caused by: java.io.FileNotFoundException: /storage/emulated/0/Download/XXXXXX.mp4.net-download: open failed: EACCES (Permission denied)

我用的jetpack compose写了一个demo，就简单下载一个文件到sd卡中，可以肯定的是权限读写都打开了并且是动态申请了

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
和网络框架没关系

1. 检查文件是否存在
2. demo是否可以下载
3. 尝试用okhttp下载文件

**Comment by artillerymans** [comment]
下载目录存在，下载的文件需要我手动创建吗应该不需要吧 华为手机可以，oppo手机就不行

**Comment by liangjingkanji** [comment]
1. 不需要你创建文件
1. 设备系统版本可能不同

网络框架没有任何针对存储权限的处理, 我认为是你自己没有处理好权限问题, 建议你尝试我说的步骤
