### ISSUE TITLE
东哥请问一下，为何scopeDialog { } 不支持预览模式，是不是我使用姿势不对

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/Net#149]
scopeDialog { } .preview  { }  第一个大括号里边的不走，

如果作用域换成scopeNetLife{}.preview  { }  才正常，这个算是bug吗？

**Comment by liangjingkanji** [comment]
算你写错了

**Comment by zkzk7749** [comment]
我的确是使用scopeNetLife{}.preview { }  这个请求网络，和绑定数据都很很正常。

但是使用scopeDialog { } .preview { } ，网络是有请求的，但是网络请求完毕以后，绑定数据就不执行了

**Comment by liangjingkanji** [comment]
请使用日志或者断点调试, 如果还有问题请fork仓库复现问题, 我再次重申不要让猜测浪费维护项目的时间

**Comment by liangjingkanji** [comment]
没有说不存在错误, 但是错误可能不是你描述的位置, 我不希望和你在这里远程对练空想瞎猜

**Comment by zkzk7749** [comment]
恩恩恩，明白东哥苦心

**Comment by zkzk7749** [comment]
东哥，我代码来了。在fragment中使用的。
 scopeNetLife {
            val data =
                Get<String>("https://wwww.baidu.com").await()
            binding.textHome.text = data
            homeViewModel.str.value = data
        }.preview {
            Log.i("aaaaaaaaaaaaaa", "预览000")
            homeViewModel.str.value?.let {
                Log.i("aaaaaaaaaaaaaa", "预览1111")
                binding.textHome.text = it
                this.cancel()
            }
        }

逻辑就是如果viewmodel有数据，就取viewmodel中的，然后停止请求网络，如果viewmodel是空，那么请求网络。
以上代码使用正常，可以达到我的目的。

但是把scopeNetLife  换成scopeDialog就不行了，网络请求可以发送请求，但是无法收到响应，
           binding.textHome.text = data
            homeViewModel.str.value = data
这两句话就无法执行了

**Comment by zkzk7749** [comment]
极大可能是我的使用方法不对，我太菜

**Comment by zkzk7749** [comment]
版本就是最新的
implementation 'com.github.liangjingkanji:Net:3.5.2'

**Comment by zkzk7749** [comment]
来彩图
![1669995288959](https://user-images.githubusercontent.com/18433246/205329181-78530463-19cc-4e5c-8f3f-71c36ac1234c.png)

**Comment by zkzk7749** [comment]
我怀疑是什么原因，让okhttp不执行了，这个是使用scopeDialog的日志
![1669997202293](https://user-images.githubusercontent.com/18433246/205335466-540ccc3d-5608-414f-a90e-f737e88c8f93.png)
