### ISSUE TITLE
scopeDialog的预览模式无法触发网络请求

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/Net#150]
## 问题描述
scopeDialog的预览没有达到我的预期。但是scopeNetLife 可以
### 期望行为
希望scopeDialog预览以后还可以走
## 如何复现
在fragment中100%复现，代码也简单，复制一下就能跑
```kotlin
scopeNetLife {
  val data =
    Get("[https://wwww.baidu.com").await(](https://wwww.baidu.com%22%29.await%28/))
  binding.textHome.text = data
  homeViewModel.str.value = data
}.preview {
  Log.i("aaaaaaaaaaaaaa", "预览000")
  homeViewModel.str.value?.let {
    Log.i("aaaaaaaaaaaaaa", "预览1111")
    binding.textHome.text = it
    this.cancel()
  }
}
```
逻辑就是如果viewmodel有数据，就取viewmodel中的，然后停止请求网络，如果viewmodel是空，那么请求网络。
以上代码使用正常，可以达到我的目的。

但是把scopeNetLife 换成scopeDialog就不行了，网络请求可以发送请求，但是无法收到响应。
详见下图
> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间
问题简单，不用fork仓库了
## 截图
![image](https://user-images.githubusercontent.com/18433246/205426807-d3ee3ee3-dfae-4b74-b3df-0df7008e210a.png)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)
这个是使用scopeDialog的日志
![image](https://user-images.githubusercontent.com/18433246/205426859-a33ded45-ac7b-41db-8f3b-01048620337c.png)

## 版本
- Net:最新版
- OkHttp: 使用最新版Net中
- Android:12
- Gradle: 7.1
- Android Studio:

**Comment by zkzk7749** [comment]
我百思不得其解，可能是我那个地方少些参数了吧，请东哥指点一二

**Comment by zkzk7749** [comment]
我拿走了干扰项，重新截图。下图是scopeDialog的，明显看出网络请求后的内容没走
![1670047593971](https://user-images.githubusercontent.com/18433246/205427227-4fa38063-6d0b-4d90-bb11-71187a73eee8.png)

**Comment by zkzk7749** [comment]
下图是scopeNetLife，可以到完成预期
![31100f55d1bb6cf34a36393a2aa6c6d](https://user-images.githubusercontent.com/18433246/205427295-8e585c99-652c-467e-ab4e-27c86d5b590d.png)

**Comment by liangjingkanji** [comment]
bug已经在dev分支被修复

1. 希望你认真fork仓库复现问题, 这样解决问题效率更高, 另外不要写什么`最新版本`的版本号

2. 如果你开启了预读模式, 我建议直接使用`scopeNetLife`, 因为读取缓存速度非常快不需要加载对话框

**Comment by zkzk7749** [comment]
感谢东哥！！接受东哥建议

**Comment by zkzk7749** [comment]
请教东哥，关于您提的第二点建议，我有个问题请教下。


我开启了预读模式，如果能读到我就保证用scopeNetLife。但万一读不到呢，我用个什么方法切换到显示对话框的模式呢？其实我前几天就在考虑这个问题，但我太菜，百撕不得其姐

**Comment by liangjingkanji** [comment]
> 请教东哥，关于您提的第二点建议，我有个问题搞不定。
> 
> 我开启了预读模式，如果能读到我就保证用scopeNetLife。但万一读不到呢，我用个什么方法切换到显示对话框的模式呢？其实我前几天就在考虑这个问题，但我太菜，百撕不得其姐

1. 这个是我考虑不周全, 请升级版本3.5.3已经修复此问题
2. 我一般都是用缺省页loading, 官方不推荐加载框中断请求(且默认情况下对话框可以点击外部取消)
