### ISSUE TITLE
Demo中Viewmodel返回Deferred后 无法调用

### ISSUE THREAD

**Issue by bibubi** [liangjingkanji/Net#151]
```     fun CoroutineScope.fetchList() = Get<String>(Api.BANNER) ```
这个应该如何调用，新手再次求救

**Comment by liangjingkanji** [comment]
```kotlin
fun CoroutineScope.fetchList() = Get<String>(Api.BANNER)
val result = fetchList().await()
```

**Comment by bibubi** [comment]
难道我AS出Bug了？
我当时也是这样调用的，但发现AS报错。
如图所示。。
![image](https://user-images.githubusercontent.com/18078927/206048869-c94db27f-c3fe-459f-8f1b-e7a8a21cc7d8.png)

**Comment by liangjingkanji** [comment]
说实话... 我建议先从Java/Kotlin语言开始学起

你这连调用方法都不会无从教起
