### ISSUE TITLE
关于content-type的问题

### ISSUE THREAD

**Issue by zhengjiong** [liangjingkanji/Net#152]
使用Post发起网络请求, 日志打印的log, content-type始终为application/json, 就算设置了mediaType = MediaConst.URLENCODED, 也不生效, 请问怎么才能设置contenttype为application/x-www-form-urlencoded呢?

scopeLife {
                    val result = Post<String>(Api.BANNER){
                        mediaType = MediaConst.URLENCODED
                        param("u_name", "drake")
                        param("pwd", "123456")
                        //json("name" to "nameValue")
                    }
                }

**Comment by liangjingkanji** [comment]
请贴上代码

**Comment by zhengjiong** [comment]
> 请贴上代码

scopeLife {
                    val result = Post<String>(Api.BANNER){
                        mediaType = MediaConst.URLENCODED
                        param("u_name", "drake")
                        param("pwd", "123456")
                        //json("name" to "nameValue")
                    }
                }

**Comment by liangjingkanji** [comment]
你这个代码不可能是`application/json`

**Comment by zhengjiong** [comment]
执行的代码:
scopeLife {
                    val result = Get<String>(Api.BANNER).await()
                    Timber.e("result=${result}")
}
打印的日志如下:

2022-12-27 15:39:38.283 14819-15298 OKPRFL_cf3b3wh_RSH      com.desaysv.shop                     V  content-type:application/json;charset=UTF-8
2022-12-27 15:39:38.284 14819-15298 OKPRFL_cf3b3wh_RSH      com.desaysv.shop                     V  date:Tue, 27 Dec 2022 07:39:38 GMT

**Comment by zhengjiong** [comment]
我看代码默认好像是open var mediaType: MediaType = MediaConst.FORM

**Comment by liangjingkanji** [comment]
> 

```
/**
 * multipart请求体的媒体类型
 */
open var mediaType: MediaType = MediaConst.FORM
```
注释有说这是`multipart请求体`的, 默认情况下并不是multipart

**Comment by liangjingkanji** [comment]
> 执行的代码: scopeLife { val result = Get(Api.BANNER).await() Timber.e("result=${result}") } 打印的日志如下:
> 
> 2022-12-27 15:39:38.283 14819-15298 OKPRFL_cf3b3wh_RSH V content-type:application/json;charset=UTF-8 2022-12-27 15:39:38.284 14819-15298 OKPRFL_cf3b3wh_RSH V date:Tue, 27 Dec 2022 07:39:38 GMT

RSH代表的是ResponseHeader, 即服务器返回给你的`contentType`. 不是请求头不是客户端能控制的

**Comment by zhengjiong** [comment]
原来是这样 我看错了
