### ISSUE TITLE
json解析疑问

### ISSUE THREAD

**Issue by kinghom** [liangjingkanji/Net#153]
## 问题描述

接口访问成功的情況下

SerializationConverter 转换器 当解析 json.getString("data").parseBody<R>(kType) 

如果解析失败(我的bean是data里面的内容) 不会跳转到 JSONException 进行 全json解析

而是跳到  ConverException

**Comment by liangjingkanji** [comment]
我无法复现问题, 请fork仓库复现问题, 或者请你来debug修复此问题(转换器代码非常简单)

**Comment by kinghom** [comment]
已经收到你的飞鸽传书啦....

**Comment by liangjingkanji** [comment]
`json.getString("data")`如果获取不到`data`会抛出JSONException

不清楚你为什么没有抛出, 请不要删掉提交问题模板, 不要让人猜测问题

**Comment by kinghom** [comment]
大佬 我fork了一份  https://github.com/kinghom/Net.git

方便测试  在SerializationConverter里面返回的json 我写死了 

测试入口在SerializationConvertFragment

现在发现导致这个com.drake.net.exception.ConvertException异常是 因为我把 errorCode 修改成 code  但是实际上json返回确实是code

**Comment by liangjingkanji** [comment]
异常捕获错误, 按照上面提交修改下为`SerializationException`即可
