### ISSUE TITLE
最新版3.5.4，无法打印网络日志

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/Net#157]
## 问题描述
最新版3.5.4，无法打印网络日志，无论是logcat还是Okhttp Profiler都无法打印。但是前一版正常

### 期望行为
可以正常打印网络日志
## 如何复现
demo100%复现
> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间
demo100%复现
## 截图
无截图
异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net: 3.5.4
- OkHttp:  4.10.0
- Android: 12
- Gradle: 7.1
- Android Studio: 2021.2.1

**Comment by liangjingkanji** [comment]
已修复
