### ISSUE TITLE
viewModel中网络请求怎么弹出dialog呢

### ISSUE THREAD

**Issue by zhengjiong** [liangjingkanji/Net#158]
scopeDialog不能在viewModel中使用, 现在没有这个扩展方法

**Comment by liangjingkanji** [comment]
创建dialog需要activity对象, 所以你不传入activity对象就不可能创建

建议直接在activity里面网络请求就好, 你位置换来换去会很麻烦

**Comment by gangoogle** [comment]
你可以viewmodel写一个 LiveData搞一个boolean值然后在baseActivity里面监听弹窗字段控制弹窗关闭显示

**Comment by qwer2y** [comment]
可以封装一下在非Activity里获取栈中顶层Activity作为对象作为默认传入
