### ISSUE TITLE
使用的是Net 3.4.6版本，抛出ResponseException，无法打印log和toast

### ISSUE THREAD

**Issue by BatterMan-Li** [liangjingkanji/Net#159]
## 问题描述
Net使用的3.4.6版本， Tooltip:1.2.1版本，首次请求会打印和toast,再次请求过程走到SerializationConverter中的ResponseException，然而无法执行全局NetErrorHandler中，故不能打印日志和toast，没有重写全局错误处理，也没有局部距离

### 期望行为
如何解决并恢复正常

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net: 3.4.6
- OkHttp: 4.9.1
- Android: 31
- Gradle: gradle-7.2-bin
- Android Studio:2021.2.1 patch2

**Comment by liangjingkanji** [comment]
无法复现此问题, 能否fork仓库复现此问题

**Comment by BatterMan-Li** [comment]
目前我也无法复现此问题，如果调试显示了Logcat和Toast，后面就会一直显示！
