### ISSUE TITLE
菜鸟反映一个问题啊

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/Net#160]
## 问题描述
 我使用demo中的RefreshTokenInterceptor 拦截器，报错
错误提示
java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
经百度后，需要加一句话就可以。加response.close()就可以，请问作者大神需不需要加到demo里边去？

**Comment by liangjingkanji** [comment]
我不清楚什么位置发生的异常, 如果你能复现希望你能修复下此问题
