### ISSUE TITLE
页面加载多个rv，每个rv点击事件相互关联，出现rv自动滚动且无法滑动到底部怎么解决？

### ISSUE THREAD

**Issue by hanxmone** [liangjingkanji/Net#162]
## 问题描述
页面加载多个rv，每个rv点击事件相互关联，出现rv自动滚动且无法滑动到底部
### 期望行为
rv滑动不应相互影响
## 如何复现
使用Net，BRV，stateLayout配置自动缺省页
rv由BRV实现->第一级checked单选->item改变触发Net网络请求->下一级rv数据刷新->导致上一级rv自动滚动到First或者无法滑动到底部？？？

## 版本
- Net:3.5.6
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
这个问题和本框架无关, 本框架没有自定义rv无法处理rv嵌套行为
