### ISSUE TITLE
Post提交json格式

### ISSUE THREAD

**Issue by gitboylovegirl** [liangjingkanji/Net#163]
## 问题描述
设置了 mediaType = MediaConst.JSON 发出的请求还是Form格式
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

![微信图片编辑_20230301142105](https://user-images.githubusercontent.com/20661387/222060652-c4e39775-3679-498b-b73e-1bab6bdcedf8.jpg)
![微信图片编辑_20230301142204](https://user-images.githubusercontent.com/20661387/222060782-2727a700-2e01-4b28-9c2c-1b8fc07c8a9d.jpg)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp:  
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
建议仔细阅读文档或者demo

1. JSON请求只需要使用`json()`方法提交参数或者自定义body
