### ISSUE TITLE
大佬，怎样和compose结合比较好

### ISSUE THREAD

**Issue by tanweis** [liangjingkanji/Net#164]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
本框架支持`热插拔形式`和BRV框架联动

但是BRV框架不属于Compose, 所以如果你要使用Compose那并没有和其他框架有什么特殊的"结合", 该怎么用就怎么用网络请求
