### ISSUE TITLE
关于版本升级后json数据解析的问题

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Net#165]
## 问题描述

刚把Net框架从3.1.2版本升级到最新的3.5.6版本，然后返回数据解析就会报错类型转换异常，换回3.1.2就没问题了😂

### 期望行为

应该是和以前3.1.2版本一样数据解析成功，东西都没改，只是Net版本升级就不行了

## 如何复现

java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.example.wanAndroid.logic.model.base.ApiPagerResponse

这是用3.1.2显示的正常，3.5.6就直接走catch了
![image](https://user-images.githubusercontent.com/54784104/222963307-c5163831-7f26-422c-8ad0-4fba3c589291.png)

![image](https://user-images.githubusercontent.com/54784104/222963432-9f7ebe7b-e755-42fe-a241-80ffc5a69a7c.png)

## 版本
- Net: 3.5.6
- OkHttp: 4.10.0
- Android: 11
- Gradle: 7.5
- Android Studio: 2022.1.1

**Comment by SaltedFish-Extreme** [comment]
这是用3.1.2请求的第一个data的数据
![微信图片_20230305215034](https://user-images.githubusercontent.com/54784104/222964536-d85d6c16-714f-4565-8843-91e40c17be4f.png)

这是用3.5.6请求的第一个data的数据
![微信图片_20230305215039](https://user-images.githubusercontent.com/54784104/222964539-39ba342b-cfc6-4ef2-a8f0-e2d05766eb94.png)

我看两个第二层data数据解析的格式不一样，原来好像是一层一层解析的，新版好像是一次全解析出来了，是不是还要json格式化之类的才能正常拿到数据😂

**Comment by liangjingkanji** [comment]
不清楚具体原因，转换器代码很简单你debug下

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 我刚才测了下，发现从3.4.12版本一直到3.5.5版本都是没问题的，到了最新版3.5.6就出现问题了😂你是不是改了啥东西，比如默认gson解析啥的😂

**Comment by SaltedFish-Extreme** [comment]
> 我也遇到了一样的问题，暂时没找的原因，急着上线，就回退版本了

我昨晚测试发现3.5.5以下的版本都没问题，可能强东哥在3.5.6上改了啥东西🤔

**Comment by liangjingkanji** [comment]
你查看git版本变更历史, 转换器本身就属于用户自己扩展的接口实现

JsonConverter并没有在3.5.6版本中有修改

你就不能自己debug下转换器的执行代码吗?

**Comment by SaltedFish-Extreme** [comment]
我debug转换器，3.5.5和3.5.6返回的fromJson数据是一样的，后面跳到这个包里的JSONConvert和ResponseExtension还有NetCoroutine之后我就看不大明白了，都是直接走最后面的代码，不知道问题出在哪，继续用3.5.5了😂

**Comment by liangjingkanji** [comment]
已经修复了, 原因是为支持Java调用, 没有兼容Gson等反射解析框架的泛型擦除问题

**Comment by SaltedFish-Extreme** [comment]
👌
