### ISSUE TITLE
列表下载

### ISSUE THREAD

**Issue by linyingfa** [liangjingkanji/Net#167]
东哥，请教下，如果RV下载，是每个item都要监听一个进度吗

**Comment by liangjingkanji** [comment]
和框架无关的问题请在交流群讨论, 因为这不是几句话能描述清楚的, 也不是只有最好的一种方案, 我希望的事集思广益. 另外我也没有多余时间去解答这种问题, 框架维护已经使用了我全部精力

另外欢迎你在demo中实现本需求示例代码并且发起pr提交

> 使用databinding实现本需求非常简单

**Comment by liangjingkanji** [comment]
你这个问题最起码也是[brv](https://github.com/liangjingkanji/BRV)有关联,  和网络请求框架完全没关系, 我将关闭此问题
