### ISSUE TITLE
大佬 GsonConverter ，嵌套的json怎么解析

### ISSUE THREAD

**Issue by bbllgo** [liangjingkanji/Net#168]
## 问题描述
  
url: https://wanandroid.com/article/list/0/json
Get<ApiPagerResponse<List<AriticleResponse>>>(Api.article + "$i1/json"){
                    converter= GsonConverter()
                }.await()
解析时把 List<AriticleResponse> 檫除了，没有解析，导致返回了null
### 期望行为
能解析出 List<AriticleResponse>
## 如何复现
 https://wanandroid.com/article/list/0/json
> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net: 3.5.7
- OkHttp: 4.10.0
- Android:
- Gradle: 7.5
- Android Studio:11.0.13

**Comment by liangjingkanji** [comment]
解析不匹配也不可能返回null

**Comment by liangjingkanji** [comment]
1. 我不知道转换器怎么写的, 我也不知道`ApiPagerResponse`怎么写的, 对于这种问题复现要求fork仓库复现问题, 如果无法复现问题我无法解决, 这是为了保证高质量bug修复所要求的, 因为在过去几年光提别人复现问题猜测问题花费的时间比框架本身时间还要多

2. 虽然我不推荐这种愚蠢的泛型方式写数据结构, 但是有人这么做也是没问题的 #165

**Comment by bbllgo** [comment]
![image](https://user-images.githubusercontent.com/121722384/230106147-e20ff9bb-00e7-4149-89b2-2e245f8540f2.png)
哦 ，就是不支持， 嵌套的方式解析
