### ISSUE TITLE
URL 转义无效，

### ISSUE THREAD

**Issue by XiaoWensc** [liangjingkanji/Net#17]
![image](https://user-images.githubusercontent.com/7828286/115533772-a4168e80-a2c9-11eb-8bf4-deb74aa358e7.png)

**Comment by liangjingkanji** [comment]
建议使用`URLEncoder.encode()`手动转码一下.  这是因为之前修复URL空格的问题导致的新BUG.   我正在重写中内部代码中.

**Comment by liangjingkanji** [comment]
版本号修改为: 2.3.16

**Comment by liangjingkanji** [comment]
最近发布新的OkHttp版本

**Comment by XiaoWensc** [comment]
okhttp遇到服务gzip 压缩时，需要解压数据。  是否能优化？

**Comment by liangjingkanji** [comment]
服务端压缩了, 那肯定得解压啊, 你应该让服务器关闭gzip.  
我目前正在3.x分支进行重构内核.  打算至少成为Android五年内最优秀的网络请求库.
