### ISSUE TITLE
net preview加载缓存之后 用RefreshLayout的刷新动画 从网络加载数据

### ISSUE THREAD

**Issue by JamesGZM** [liangjingkanji/Net#170]
## 问题描述
使用Net的preview加载缓存 之后 继续加载网络数据的时候 需要加载动画 怎么处理呢？
### 期望行为
使用Net的preview加载缓存 之后 继续加载网络数据 RefreshLayout弹出刷新动画对应网络加载
## 如何复现

https://github.com/JamesGZM/BRV/blob/master/sample/src/main/java/com/drake/brv/sample/ui/fragment/home/HomeListFragment.kt
类似代码在这里面 mock看不出来缓存的效果 

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间
https://github.com/JamesGZM/BRV/blob/master/sample/src/main/java/com/drake/brv/sample/ui/fragment/home/HomeListFragment.kt

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- BRV:1.4.1
- Net:3.5.8
- OkHttp: 4.10.0
- Android:12
- Gradle: 7.5
- Android Studio:Android Studio Electric Eel | 2022.1.1 Patch 2

**Comment by liangjingkanji** [comment]
你为什么不尝试看下这个`preview`方法有什么参数可以实现这种行为

**Comment by liangjingkanji** [comment]
对于我辛苦写的文档和方法注释视而不见会让我感到失望的

**Comment by JamesGZM** [comment]
https://github.com/JamesGZM/BRV/blob/master/sample/src/main/java/com/drake/brv/sample/ui/fragment/home/HomeListFragment.kt 
进行了一部分修改 目前效果接近我想的那个效果 但是还不完美

**Comment by liangjingkanji** [comment]
为什么同时调用`autoRefresh`和`showLoading`, 感觉这是无意义的代码

**Comment by liangjingkanji** [comment]
不过我发现你有判断index==1才启用`预读`, 这种需求我认为值得考虑为更为简化

**Comment by JamesGZM** [comment]
> 为什么同时调用`autoRefresh`和`showLoading`, 感觉这是无意义的代码
> 
> 两者只需要选择一个即可

因为我想让它一开始走 loading 然后加载缓存 再去访问网络显示 Refresh
