### ISSUE TITLE
关于数据获取问题

### ISSUE THREAD

**Issue by byjjack** [liangjingkanji/Net#172]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图
![8a37988f79a990c9589846d048ac2d2](https://github.com/liangjingkanji/Net/assets/19277478/524efd7f-2a3d-49f8-8182-1078b4874d1b)
![1c0251178310aa6e56dd1497ca342be](https://github.com/liangjingkanji/Net/assets/19277478/a852a609-a347-4b5a-b380-1aebfc17d29a)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net: 3.5.8
- OkHttp: 4.10.0
- Android:
- Gradle: 7.2.1
- Android Studio:

**Comment by byjjack** [comment]
拦截器 忘说了使用的是 SerializationConverter 和demo里边一样

**Comment by liangjingkanji** [comment]
光看你的代码没发现有什么问题

建议你看下LogCat是否输出Net相关日志, 你自己调用了`catch`方法所以日志会按照你自己的输出, 建议你检查下是否有日志

**Comment by byjjack** [comment]
![7f4129e1f62d8145890607dada016ca](https://github.com/liangjingkanji/Net/assets/19277478/354ee6a6-d206-4409-9b1e-b45c715f2447)

看了一下日志说是LoginResult找不到序列化程序，我不是已经把他添加了吗

**Comment by liangjingkanji** [comment]
你这应该是`kotlin-serialize`解析框架没有正确依赖导致, 未添加kapt插件是吗?

**Comment by byjjack** [comment]
是的我没有引入kapt 插件，正在引入，然后那个kotlin-serialize 框架也没有引入全，然后做了如下修改，就是导入的时候比较慢，等我处理好了再看看结果如何
![c81ddc2ecc3cc490a8695a2b21376af](https://github.com/liangjingkanji/Net/assets/19277478/84d78ea8-30cc-4192-98b9-aae992974712)
![bcb2a1c8036d54641dcc50c80a8e919](https://github.com/liangjingkanji/Net/assets/19277478/cf272e7a-d25e-4b65-8202-1468a41091d9)

**Comment by byjjack** [comment]
确实是上述的问题，但是现在还是拿不到数据，找不到问题所在
![6829c444acdaac0d85469ae280a6145](https://github.com/liangjingkanji/Net/assets/19277478/9f26b65a-2f1d-4e06-98ae-46c1c05b5b6c)
![7f6bbbfe7deae634060d77e0e55afee](https://github.com/liangjingkanji/Net/assets/19277478/000059b5-8615-489d-98d0-c0a9eba6c3f9)

**Comment by byjjack** [comment]
![62f4bde63b1f74ad25fe126ad202f46](https://github.com/liangjingkanji/Net/assets/19277478/6e534636-1707-426e-8528-ddaa75922fb9)
具体返回的数据及打印后的数据

**Comment by liangjingkanji** [comment]
你日志都输出来了为什么你说拿不到数据

而且什么叫拿不到数据? await后面的代码执行到了吗?

**Comment by liangjingkanji** [comment]
执行到了就代表网络请求没问题, 至于没有数据得看你数据转换器怎么执行的了

你可以试下直接使用ks进行json反序列化看是否有问题, 或者debug数据转换器

如果你不想在这里回合制一般猜来猜去, 就自己多尝试, 最好能fork本仓库在demo中复现问题, 我可以直接帮你看代码, 否则你这个问题我感觉还得猜好几天, 我在issues里面也是不断强调减少这种云猜测云排查

或者你去群里面咨询此问题

**Comment by byjjack** [comment]
嗯嗯，问题已经解决了 ，转换器那块我写错了，很是抱歉，然后咱们这个群是啥，我没有找到
<img width="704" alt="截屏2023-05-13 16 21 15" src="https://github.com/liangjingkanji/Net/assets/19277478/3e9f026d-ad6d-4f52-aafb-378d74808d95">
