### ISSUE TITLE
想问下在转换器里ResponseException 里的tag能在单例里边拿到吗

### ISSUE THREAD

**Issue by byjjack** [liangjingkanji/Net#173]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间
## 截图

![1dabe857fea19a2a16b6dd1b1803ee7](https://github.com/liangjingkanji/Net/assets/19277478/49c3df86-e33c-4d32-9425-e7cf50b7aebf)
![74a7728e531fe41ad90656c99dc7d99](https://github.com/liangjingkanji/Net/assets/19277478/13d9bc4e-6fe1-45ba-be1f-47d867b1b10d)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net: 3.5.8
- OkHttp: 4.10.0
- Android:
- Gradle: 
- Android Studio:

**Comment by TxcA** [comment]
``` kotlin
scope {
    ...
}.catch {error->
      if (error is ResponseException){
          error.tag
      }
}
```

**Comment by byjjack** [comment]
好的十分感谢，我这就试一下

**Comment by byjjack** [comment]
成功了
