### ISSUE TITLE
android14网络请求失败，无任何log

### ISSUE THREAD

**Issue by Linmuge** [liangjingkanji/Net#175]
## 问题描述
android14 混淆后网络请求失败，无任何log，okhttp可以正常请求，混淆前可以正常请求

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net: 3.5.8
- OkHttp: 4.11.0
- Android: 14
- Gradle: 8.1.1
- Android Studio: Android Studio Hedgehog | 2023.1.1 Canary 5

**Comment by liangjingkanji** [comment]
没有任何log我也无法排查问题，建议你添加日志，我这边无法复现此问题

**Comment by liangjingkanji** [comment]
或者你可以混淆本仓库的demo然后复现此问题

**Comment by liangjingkanji** [comment]
你把Gradle升级太高导致我项目都跑不起来

**Comment by liangjingkanji** [comment]
是让我点击`GET`发起请求吗?  我点击以后立刻显示了日志

你是不是不知道`release`构建类型默认会关闭日志输出? 需要使用配置`debuggable`属性启用日志

**Comment by Linmuge** [comment]
问题已解决，感谢解答，又长了点知识😂
