### ISSUE TITLE
接口每次调成功后, 都会弹toast 返回信息, 怎么关闭,不让它弹

### ISSUE THREAD

**Issue by D-zy** [liangjingkanji/Net#177]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
你看demo请求成功会弹Toast吗? 我认为是你代码编写有问题

**Comment by D-zy** [comment]
已解决
