### ISSUE TITLE
Compose分支可以完全去掉appcompat吗？

### ISSUE THREAD

**Issue by hmy65** [liangjingkanji/Net#178]
新项目纯kotlin+compose不想引入appcompat。
大强子有计划以后发布两个分支吗？

**Comment by liangjingkanji** [comment]
有空我会迁移仓库的, 有计划删除appcompat依赖, 不过那样就不能配合BRV实现自动化的网络请求处理了

另外我也不会Compose我也没用到Compose, 等我找到会Compose的作者接手也许更快

**Comment by hmy65** [comment]
> 有空我会迁移仓库的(目前工作紧张而且有优先级更高的bug待修复)
> 
> 有计划删除appcompat依赖发布Compose分支版本, 不过那样就不能配合BRV实现自动化的网络请求处理了
> 
> 另外我也不会Compose我也没用到Compose, 等我找到会Compose的作者接手也许更快, 纯Compose项目你就得多学会多靠自己了

不多说了，东哥牛逼。
不过更希望有kotlin multiplatform的版本，只依赖okhttp和coroutines。

**Comment by liangjingkanji** [comment]
你的希望几乎不可能

1. 首先只依赖okhttp就会砍去大量的功能, 这会失去框架的核心竞争力
2. 其次我不会那么多平台的编写框架能力
3. 996工作不允许我有时间在开源投入如此巨大的精力

光Android平台的需求我就无法实现完, 跨平台我没有那个能力, 还是得靠你们来扩充了

**Comment by liangjingkanji** [comment]
没有跨平台开发的技术, 工作量巨大我无法完成
