### ISSUE TITLE
有没有ProtoBuf使用serialization的例子

### ISSUE THREAD

**Issue by hanqingkai** [liangjingkanji/Net#179]
## 问题描述
从https://juejin.cn/post/6963676982651387935这篇文章过来的，最近在搞长连接ProtoBuf的项目，ProtoBuf用起来真费劲，不知道有没有相关的例子推荐，万分感谢
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
本仓库就有使用例子
