### ISSUE TITLE
协程作用域使用问题

### ISSUE THREAD

**Issue by eegoworld** [liangjingkanji/Net#183]
菜鸟问下：
![image](https://github.com/liangjingkanji/Net/assets/139188159/c61985d8-a542-4840-a2d4-0174a4b0ddc5)

背景：
代码1，执行生成网络路径，然后由代码2 提交其网络路径，
问题：
执行了1后，代码2，没有执行 ， println("commit 2222")  也没打打印，这是为毛 （还有其他的写法？）

**Comment by eegoworld** [comment]
有其他方式的写法吗？

**Comment by liangjingkanji** [comment]
我也没看出来为啥, 估计是发生异常走到了catch(如果你写了的情况下, 如果没写走到全局错误处理去), 你检查下logcat有没有日志输出

**Comment by eegoworld** [comment]
好的，我排查下

**Comment by liangjingkanji** [comment]
长时间无回复本问题关闭
