### ISSUE TITLE
网络请求该怎么封装？

### ISSUE THREAD

**Issue by eegoworld** [liangjingkanji/Net#184]
![image](https://github.com/liangjingkanji/Net/assets/139188159/8233739d-f131-4626-983c-9909dead9d6d)

如果有多个相同的请求，该怎么封装，把data 返回出去？

看了demo ,用这种方式
![image](https://github.com/liangjingkanji/Net/assets/139188159/3698175a-6945-464c-8450-a9772fe255e0)

**Comment by liangjingkanji** [comment]
<img width="823" alt="image" src="https://github.com/liangjingkanji/Net/assets/21078112/350c4864-e757-4f30-8352-8dbbbd4ce2ed">

协程封装的都是挂起函数, 不可能封装作用域返回结果的(这属于函数回调)

作用域可以看做If等语句, 是需要每次手写的, 并且作用域内部可能存在多个挂起任务, 具体看demo如何封装的吧
