### ISSUE TITLE
要弹框，怎么处理

### ISSUE THREAD

**Issue by eegoworld** [liangjingkanji/Net#185]
用实体类解析，弹框就没法实现把，内部把 code 的逻辑处理了
![image](https://github.com/liangjingkanji/Net/assets/139188159/473100aa-b439-47c2-8d3b-e00e3a280c6e)

处理方式：
 去除泛型解析，用string解析，然后手动解析，去判断？

![image](https://github.com/liangjingkanji/Net/assets/139188159/0ccd5460-a686-4f2b-93ff-f7d4b170a9ff)

**Comment by liangjingkanji** [comment]
大多数业务设计上, 接口请求成功并不会出现`code/msg`这种字段, 仅错误情况下才需要

那么既然是错误情况, 你在catch里面去根据异常对象获取`code/msg`然后弹窗不就好了

另外实体类解析也不是强制你必须要剔除掉code/msg


令我感到不可思议, 明明code都不为`正确值`为什么你依然认为应该在scope里面处理? 那你认为什么情况下才需要catch?

**Comment by liangjingkanji** [comment]
善用`异常处理`是成熟开发者必备技能

**Comment by eegoworld** [comment]
一下，没转换过来，新框架需要适应

**Comment by eegoworld** [comment]
get 不到大佬的精髓

**Comment by liangjingkanji** [comment]
下次买个Mac吧

**Comment by eegoworld** [comment]
![image](https://github.com/liangjingkanji/Net/assets/139188159/893fd0d7-fb61-4b39-8389-9aeed266d8f5)

后端 msg, 貌似取不到

**Comment by eegoworld** [comment]
![image](https://github.com/liangjingkanji/Net/assets/139188159/a8dbba26-9619-49bd-b006-a4233972b3ce)
我这里怎么没有那个 it.code ,提示没有

**Comment by liangjingkanji** [comment]
你去看下转换器里面怎么创建ResponseException的吧, 我有点解释不清楚这种问题

**Comment by eegoworld** [comment]
![image](https://github.com/liangjingkanji/Net/assets/139188159/84861597-f9ab-4559-842a-70332faf5423)
知道了，大佬受惊了，请你喝杯奶茶

**Comment by eegoworld** [comment]
很好框架，我要打赏

**Comment by liangjingkanji** [comment]
我是不喜欢群里抢红包的那种人

**Comment by liangjingkanji** [comment]
与其打赏不如加入吧, 开源的目的是为了集思广益贡献代码
