### ISSUE TITLE
ViewModel封装请求动作问题

### ISSUE THREAD

**Issue by NEIL-ORZ** [liangjingkanji/Net#186]
## 问题描述
在demo中，ViewModel 中的 fetchList 是类内扩展，类外无法调用，这种情况如何封装
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图
![image](https://github.com/liangjingkanji/Net/assets/66617546/8114db3b-0633-4a8e-8133-a76742fa35db)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
已经更新sample的使用案例了, 添加更多注释和使用案例

**Comment by liangjingkanji** [comment]
现在写安卓的怎么都这么纠结于一定要把所有代码放在ViewModel里面, 甚至愿意牺牲代码可读性和写更多的代码

关于这个问题建议你加群去问问别人吧

**Comment by NEIL-ORZ** [comment]
谢谢解答

**Comment by liangjingkanji** [comment]
欢迎加入开源项目, 补全不足
