### ISSUE TITLE
上传进度回调Progress，finish字段失效

### ISSUE THREAD

**Issue by 530l** [liangjingkanji/Net#187]
## 问题描述
```kotlin
Post<ArrayData>("xxxxxxxxx") {
  param("fileData", getAssetsFile())
      addUploadListener(object : ProgressListener() {
        override fun onProgress(p: Progress) {
            activity?.runOnUiThread {
                Log.i(
                    "Progress",
                    "上传进度: ${p.progress()}% 上传速度: ${p.speedSize()}     " +
                            "\n\n文件大小: ${p.totalSize()}  已上传: ${p.currentSize()}  剩余大小: ${p.remainSize()}" +
                            "\n\n已使用时间: ${p.useTime()}  剩余时间: ${p.remainTime()}  ${p.finish}"
                )
            }
  }
}
```

东哥，问下，上传文件，p.finish这个字段是 false， 影响这个字段逻辑有那些，上传到服务端，服务端上传 oss

```kotlin
2023-07-17 18:24:13.225 15843-15843/com.drake.net.sample I/Progress: 上传进度: 0% 上传速度: 0 B     
    
    文件大小: 2.70 MB  已上传: 8.19 kB  剩余大小: 2.69 MB
    
    已使用时间: 00:00  剩余时间: 00:00  false
    
    
2023-07-17 18:24:13.445 15843-15843/com.drake.net.sample I/Progress: 上传进度: 100% 上传速度: 12.12 MB     
    
    文件大小: 2.70 MB  已上传: 2.70 MB  剩余大小: 0 B
    
    已使用时间: 00:00  剩余时间: 00:00  false
```
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:3.5.8
- OkHttp: 4.10.0
- Android: 13
- Gradle: 7.0
- Android Studio:Android Studio Bumblebee | 2021.1.1 Patch 2

**Comment by liangjingkanji** [comment]
我也不清楚我需要去阅读源码才能知道

**Comment by liangjingkanji** [comment]
复现不出来你说的这个问题, 建议你要么fork仓库要么自己debug排查下finish字段是否未执行到

**Comment by 530l** [comment]
查看源码，NetResponseBody中的read（）方法中  progressListeners size =0 ,而这个progressListeners在NetOkHttpInterceptor中，只设置了RequestBody的
val reqBody = request.body?.toNetRequestBody(request.uploadListeners()) ，并没有set ResponseBody的监听，不知道是不是这个导致是 progressListeners zise =0.，没有进入条件判断。

**Comment by liangjingkanji** [comment]
你确定没有吗? 你查下`toNetResponseBody`的调用方式吧, 而且如果没有监听器等于0那么压根没有进度, 何来的`finish=false`

**Comment by 530l** [comment]
progress.finish = true 只有 2 处赋值为 true ，一处是 下载校验 md5  设置为 true 。
  还有一处是NetResponseBody的 read方法
`  progressListeners.forEach { progressListener ->
                        progressListener.intervalByteCount += if (bytesRead != -1L) bytesRead else 0
                        val currentInterval = currentElapsedTime - progressListener.elapsedTime
                        if (!progress.finish && (readByteCount == contentLength || bytesRead == -1L || currentInterval >= progressListener.interval)) {
                            if (readByteCount == contentLength || bytesRead == -1L) {
                                progress.finish = true
                            }
                            progressListener.onProgress(
                                progress.apply {
                                    currentByteCount = readByteCount
                                    totalByteCount = contentLength
                                    intervalByteCount = progressListener.intervalByteCount
                                    intervalTime = currentInterval
                                }
                            )
                            progressListener.elapsedTime = currentElapsedTime
                            progressListener.intervalByteCount = 0L
                        }
                    }`
<img width="983" alt="image" src="https://github.com/liangjingkanji/Net/assets/14791260/03b69a68-e4f9-4d20-999b-d23d595f5055">

上传进度有值，值是从NetRequestBody 的write方法 progressListener.onProgress更新的。

**Comment by liangjingkanji** [comment]
上传在`toNetRequestBody()`中传入
<img width="574" alt="image" src="https://github.com/liangjingkanji/Net/assets/21078112/a0f2ee14-c0f4-45ea-9167-40afe348e863">

你看下`finish = true`这条件走到没有吧

**Comment by 530l** [comment]
那就是 finish 这个字段只是下载情景才有使用的。上传没用的

**Comment by liangjingkanji** [comment]
那你发现问题所在了, 上传逻辑漏了, 此问题会尽快修复
