### ISSUE TITLE
keep okhttp3.** { *; }的原因请教

### ISSUE THREAD

**Issue by hmy65** [liangjingkanji/Net#194]
## 问题描述

请教强子，
为什么要
-keep class okhttp3.** { *; }
OKhttp3自带规则会有啥问题吗？

**Comment by liangjingkanji** [comment]
有使用反射获取OkHttp未公开函数和变量

因为Net是基于[OkHttp](https://github.com/square/okhttp)/协程的非侵入式框架(可使用所有Api), 所以没有封闭OkHttp的Api

**Comment by hmy65** [comment]
好的感谢 大强子

**Comment by liangjingkanji** [comment]
另外不混淆Exception是为了方便开发者上传异常堆栈信息到日志平台, 来区分错误
```kotlin
-keep class com.drake.net.exception.** { *; }
```

建议项目中任何异常都不要混淆
