### ISSUE TITLE
开发文档里的BubbleDialog是哪个？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Net#196]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

![image](https://github.com/liangjingkanji/Net/assets/54784104/271be6cf-f956-42fe-8a57-3c92160da1f5)

## 版本
- Net: 3.6.0
- OkHttp: 4.11.0
- Android: 11
- Gradle: 8.1.1
- Android Studio: 2022.2.1

**Comment by liangjingkanji** [comment]
这不属于Net框架内容, 第三方依赖库自己搜下就能知道了

属于[Tooltip](https://github.com/liangjingkanji/Tooltip)库

**Comment by liangjingkanji** [comment]
你也是无厘头, 文档都打开了你问这是什么库?

**Comment by SaltedFish-Extreme** [comment]
😅没看到，我还以为是这个库的链接🤔

**Comment by SaltedFish-Extreme** [comment]
我还专门搜了这个，结果也不是😂

**Comment by liangjingkanji** [comment]
下次看下右上角或者左上角名字吧

**Comment by SaltedFish-Extreme** [comment]
👌
