### ISSUE TITLE
scopeDialog不能全局配置 点击外部/按返回键 取消显示吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Net#197]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net: 3.6.0
- OkHttp: 4.11.0
- Android: 11
- Gradle: 8.1.1
- Android Studio: 2022.2.1

**Comment by SaltedFish-Extreme** [comment]
默认值是可以点击外部取消，这样的话，每次用scopeDialog，都要写cancelable = false，怕忘了，还有点多余，要是可以全局配置就好了🤔

**Comment by SaltedFish-Extreme** [comment]
我现在用的自定义对话框，设置`setCanceledOnTouchOutside`有用，但是`setCancelable`好像没用，按返回键还是会取消对话框

````kotlin
//全局加载中对话框配置
            setDialogFactory {
                WaitDialog.Builder(it).apply {
                    setMessage(getString(R.string.load))
                    //弹窗显示中不可取消
                    setCancelable(false)
                    setCanceledOnTouchOutside(false)
                }
            }
````

**Comment by liangjingkanji** [comment]
不知道什么问题, 你可以看下`DialogCoroutineScope`尝试调试下

如果自己解决不了可以fork仓库复现下该问题发地址

**Comment by SaltedFish-Extreme** [comment]
就是源码里的这个啊，能不能全局配置对话框不可取消，在初始化框架的时候setDialogFactory的时候配置

![image](https://github.com/liangjingkanji/Net/assets/54784104/cc72ab4d-4ff6-4cca-a80e-2ec4e662bbd2)

**Comment by liangjingkanji** [comment]
看起来你找到问题所在了, 默认值问题

**Comment by SaltedFish-Extreme** [comment]
嗯，不好意思之前描述的不够清楚😂这个地方没法在全局配置修改，只能在使用的时候设置，所以想问问老哥能不能提供下全局修改的方式😥

**Comment by liangjingkanji** [comment]
这个问题晚点有空修复, 你要是能立刻修复我可以马上pr

**Comment by liangjingkanji** [comment]
能提供你的fork吗? 方便我测试

**Comment by SaltedFish-Extreme** [comment]
好的，等晚上我提供下fork

**Comment by SaltedFish-Extreme** [comment]
老哥修复的好快啊😂我昨晚用家里电脑整到十点半，这个项目都还没构建完，实在不行了就睡了，准备今天回公司再整😢

**Comment by liangjingkanji** [comment]
不想耽误你项目进度, 我并不是什么时候都有空的

**Comment by SaltedFish-Extreme** [comment]
好的，不好意思麻烦老哥了😘
