### ISSUE TITLE
只能识别android4.0吗

### ISSUE THREAD

**Issue by ChaiChai210** [liangjingkanji/Net#2]
This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer.

**Comment by liangjingkanji** [comment]
Gradle版本过高吧, 建议升级下AndroidStudio, 或者你手动修改下Gradle插件版本, 在项目根目录的build.gradle

**Comment by liangjingkanji** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [滑动多选](https://trello.com/c/Tco12umS/1-%E6%BB%91%E5%8A%A8%E5%A4%9A%E9%80%89)
