### ISSUE TITLE
3.5.8升级后续版本混淆后,Gson解析数据时异常

### ISSUE THREAD

**Issue by qq425729** [liangjingkanji/Net#201]
## 问题描述
Caused by: java.lang.RuntimeException: Missing type parameter
## 如何复现
3.5.8后续版本混淆后
> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图
![image](https://github.com/liangjingkanji/Net/assets/8380579/049151c1-cec5-42d6-8c00-f670e1ce94c1)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
我无法复现该问题, 请你在Net的sample中复现此问题, 我会以最快速度解决

**Comment by kangxibin** [comment]
agp8开始 会默认开启这个fullMode，他不兼容自定义的Proguard混淆规则，在项目的gradle.properties中设置android.enableR8.fullMode=false就行了
![2620fc7af82f06451245f7a5cbb6982c](https://github.com/liangjingkanji/Net/assets/35134915/d3effa2a-c6c0-40b3-9196-8d4c5f1edb61)

**Comment by qq425729** [comment]
已解决,非常感谢
