### ISSUE TITLE
下载文件后的时候相关的问题

### ISSUE THREAD

**Issue by artillerymans** [liangjingkanji/Net#204]
## 问题描述
![image](https://github.com/liangjingkanji/Net/assets/16060581/57b795eb-a01c-49ff-937b-9e2568d025e3)
这个是下载时候的代码
其中 目录路径 以及文件 名称 
fileName -> png_99c818cbd2694aa8ac6e86b7f6c88e02.jpg
dir -> /storage/emulated/0/Android/data/包名/files/Download/Chat

### 期望行为
按道理 应该生成的文件 "/storage/emulated/0/Android/data/com.artillery.cg/files/Download/Chat/png_99c818cbd2694aa8ac6e86b7f6c88e02.jpg"
实际情况是
![image](https://github.com/liangjingkanji/Net/assets/16060581/2fd5e416-1303-4e0b-a0b5-8e4b683a2d97)

如果是没有权限的的Chat这个文件都不会生成 所以我不知道是不是我下载时候的配置问题

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by artillerymans** [comment]
我换成内部空间也是一样 只会生成一个Chat文件

**Comment by artillerymans** [comment]
代码写错了 原来要用context.filesDir 。。。。。。。。

**Comment by liangjingkanji** [comment]
并没有限制你传的目录路径, 更不会只能使用`context.filesDir`
