### ISSUE TITLE
当minifyEnabled=true时，项目解析出现异常

### ISSUE THREAD

**Issue by yomigatz** [liangjingkanji/Net#207]
## 问题描述
当我开启minifyEnabled=true时，项目解析出现问题
## 如何复现
修改build.gradle，
`    buildTypes {

        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }

        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }`
> 
## 截图
![image](https://github.com/liangjingkanji/Net/assets/30566819/2a2e3845-e1ea-4f23-afb6-dceb3ced9e83)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:3.6.2
- OkHttp: 4.10.0
- Android: compileSdkVersion 30
- Gradle: gradle-7.2-bin
- Android Studio: Android Studio Flamingo | 2022.2.1 Patch 1

**Comment by yomigatz** [comment]
大概率时混淆的问题导致，库应该在Android上“原样”工作。如果使用的是proguard，则需要将此添加到proguard-rules.pro：
或者将数据模型添加到忽略文件中。
`-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.SerializationKt
-keep,includedescriptorclasses class com.yourcompany.yourpackage.**$$serializer { *; } # <-- change package name to your app's
-keepclassmembers class com.yourcompany.yourpackage.** { # <-- change package name to your app's
    *** Companion;
}
-keepclasseswithmembers class com.yourcompany.yourpackage.** { # <-- change package name to your app's
    kotlinx.serialization.KSerializer serializer(...);
}`

**Comment by yomigatz** [comment]
因为我是在lib中配置的项目，所以混淆需要在build.gradle中配置
`consumerProguardFiles "consumer-rules.pro"`
然后将混淆规则配置到consumer-rules.pro文件中，
至此，我的问题解决了。

**Comment by liangjingkanji** [comment]
因为序列化框架使用注解的问题

或者建议你还有Jackson取代kotlin-serialization, 他是使用反射反序列化Json
