### ISSUE TITLE
有没有Websocket Api场景下的封装

### ISSUE THREAD

**Issue by artillerymans** [liangjingkanji/Net#209]
## 问题描述
类似于百度实时语音API 一样的封装 https://ai.baidu.com/ai-doc/SPEECH/2k5dllqxj

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
没有
