### ISSUE TITLE
东哥，有没有专门搞下载库的意思

### ISSUE THREAD

**Issue by Reginer** [liangjingkanji/Net#214]
## 问题描述

 这里的下载对类似应用市场那种场景，比如一处开始下载，全局都能监听，获取下载记录，下载任务等没有直接支持

### 期望行为

我发现现在没有还在维护的下载库了，东哥有想法搞一个吗

**Comment by liangjingkanji** [comment]
你仔细看下文档或者函数

**Comment by Reginer** [comment]
是这里的吧，没有获取下载记录的api吧，以及传一个集合链接只需要设置保存文件夹这种的吧
![image](https://github.com/liangjingkanji/Net/assets/12568257/a378b38e-7615-4d69-9763-f21087357b4c)

**Comment by liangjingkanji** [comment]
刚在外面吃饭, 回来发现文档并没有提及全局进度问题

1. 任何位置可添加进度监听器
<img width="486" alt="image" src="https://github.com/liangjingkanji/Net/assets/21078112/773c288f-f8ef-42e3-93a1-f2f2cc7646f6">

2. `getRequestById`获取Request然后可以获取对应所有的进度监听

**Comment by Reginer** [comment]
哦我瞧一下代码里的

**Comment by liangjingkanji** [comment]
我只是在社区分享自己的经验罢了, 对于个人没用到的功能无力新增, 工作繁忙且技术有限

维护bug只是我对使用者负责, 欢迎其他人分享你的项目所需代码实现

Android开发者已经不愿意参与开源行为, 这和官方不断废弃以前生态也有关, 以后多靠自己吧

**Comment by Reginer** [comment]
确实，发现在2020年附近，有很多开源项目都断掉了。

**Comment by liangjingkanji** [comment]
> 确实，发现在2020年附近，有很多开源项目都断掉了。

1. 官方决策失误, 自行分流开发者
2. 都发现卖课和公众号才是取之不尽
3. 开源没收益, 还得被人黑

**Comment by liangjingkanji** [comment]
你看issues里面有多少是bug, 几乎都是要求教他怎么写业务代码

**Comment by Reginer** [comment]
哈哈哈，是这样，我自己也是希望找一个库可以满足自己的需求，就爱吃现成的
