### ISSUE TITLE
此框架会请求2次接口问题

### ISSUE THREAD

**Issue by stars-one** [liangjingkanji/Net#215]
## 问题描述

对接微信登录,因为此框架会请求2次接口导致无法获取微信登录的access_token

> 对应微信接口文档: https://developers.weixin.qq.com/doc/oplatform/Mobile_App/WeChat_Login/Authorized_API_call_UnionID.html

```
val url  = ""
scope {
                    val gson = Gson()

                    try {
                        //get请求,返回数据
                        val url =
                            "https://api.weixin.qq.com/sns/oauth2/access_token?appid=$appId&secret=$appSecret&code=${code}&grant_type=authorization_code"

                       val resp = Get<String>(url).await()
}
```

返回resp数据:

```json
{
  "errcode": 40163,
  "errmsg": "code been used"
}
```

我自己改用了okhttp去请求就解决了问题

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
1. 请求两次, 你是写了什么拦截器吗? 
2. 你能在demo复现2次请求吗?

**Comment by Gu1nBz** [comment]
把net从你的项目中移除 可能就不会请求两次了

**Comment by stars-one** [comment]
加了拦截器的原因
