### ISSUE TITLE
关闭网络之后发起请求，app直接崩溃了，不走ErrorHandler的onError方法

### ISSUE THREAD

**Issue by BLOODMAGEBURT** [liangjingkanji/Net#217]
## 问题描述
版本：3.6.4
请求方式：
![image](https://github.com/liangjingkanji/Net/assets/16059706/837f49af-ea4d-41c7-a5be-6f1a7034495f)
报错信息：
![image](https://github.com/liangjingkanji/Net/assets/16059706/9f1b1474-66b2-46ac-a221-c06e54f33866)

## 如何复现
关闭网络，或者请求一个连接不上的Host，都会触发这个错误
> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
你使用的不是net提供的协程作用域, 那就需要你自己捕获异常, 否则就会崩溃

这是协程使用基础

**Comment by BLOODMAGEBURT** [comment]
脑子一时没有转过来
