### ISSUE TITLE
支持请求失败重试吗？

### ISSUE THREAD

**Issue by hluck** [liangjingkanji/Net#221]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
拦截器可以实现, Net应该自带一个RetryInterceptor

不过从实现角度, 你加这种逻辑会在网络不好情况下严重阻塞用户交互, 因为大部分情况下请求失败你重试几次也还是会失败
