### ISSUE TITLE
提示 URLParseException 地址错误

### ISSUE THREAD

**Issue by byjjack** [liangjingkanji/Net#223]
## 问题描述
连接网络后就提示这个错误，在api 接口调试都正常但是打开app 联网的时候出现了这个错误

### 期望行为
这个错误的原因
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

![7fe18010c1101ea893e153fab5cd685](https://github.com/liangjingkanji/Net/assets/19277478/2c1a3cd3-a61a-4a96-aa0a-d4c6639470da)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:3.6.4
- OkHttp: 4.10.0
- Android: 虚拟机
- Gradle: 8.4
- Android Studio: Iguana

**Comment by liangjingkanji** [comment]
错误已经提示要求请求路径`https`或`http`开头
