### ISSUE TITLE
大佬，后续有计划适配Cronet吗？

### ISSUE THREAD

**Issue by guozhiqiang123** [liangjingkanji/Net#226]
Cronet在性能上好像比OkHttp更优异一些。
大佬后面会在此库上适配Cronet，或者单开一个库的计划吗？
[Cronet](https://developer.android.google.cn/develop/connectivity/cronet?hl=zh-cn)

**Comment by liangjingkanji** [comment]
"性能好像更优异一些"

我认为项目不需要这虚无缥缈的性能, 更需要的是OkHttp在Android上的生态和用户基数, 并且有更多更好的功能代码未实现

这是开源项目, 如果你项目很需要, 并且已经完成对Net的改造可以合并PR

## 愚公移山
感觉很多Android开发者像是"愚公", 修条路就能解决的事非得把山给平了
> 好像Fragmenet性能更好, 所以我要把项目页面全部改成Fragment, 为此整个项目重构, 不支持Fragment的三方框架全部替换, 然后交互动画自己写, 最后一看结果又累bug又多工作负担更重了, 收获页面打开速度提升10ms
