### ISSUE TITLE
Get 请求如何参数数组？

### ISSUE THREAD

**Issue by querli** [liangjingkanji/Net#227]
## 问题描述
目前使用Get 请求传参数组，使用想相同的key,最后的key value会更新掉之前的相同的key value,请问如何解决？

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
试下 `setQuery` 吧, 我不确定是否支持, 如果还有问题请你自己拼URL或者给Okhttp反馈问题

你这种重复Get参数, 后端应该也拿不到吧

**Comment by querli** [comment]
谢东哥，升级Net最新的版本的库，使用addQuery 可以完成数组请求
