### ISSUE TITLE
超时的设置问题

### ISSUE THREAD

**Issue by ail36413** [liangjingkanji/Net#230]
如何修改单个接口的超时时间呢?
Post<String>("url") {
        setClient { 
            readTimeout(3, TimeUnit.MINUTES)
            writeTimeout(3, TimeUnit.MINUTES)
        }
    }.await()
    这种改法是不是全局的超时时间都被修改了？

**Comment by liangjingkanji** [comment]
你点开函数看下

**Comment by ail36413** [comment]
奇怪了，那我默认没有去修改全局的配置，就一个接口改了超时时间。我把服务器断点了。
scopeDialog {} 过了10s，还是不会取消掉

**Comment by liangjingkanji** [comment]
Net只是基于OkHttp封装, 这种问题你去给Okhttp作者提isseus咨询吧

另外超时时间有三个值, 你只修改了2个值
