### ISSUE TITLE
ViewModel　在2.8.2版本API有问题

### ISSUE THREAD

**Issue by Lyphy999** [liangjingkanji/Net#233]
## 问题描述
   升级　androidx.lifecycle:lifecycle-viewmodel-ktx　到　2.8.2，
　框架中的　Scope.kt   viewModel.setTagIfAbsent，已经去除了该方法
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:  3.6.4
- OkHttp: 
- Android:
- Gradle: 
- Android Studio: Android Studio Koala | 2024.1.1

**Comment by liangjingkanji** [comment]
依赖发出来下

**Comment by gangoogle** [comment]
我也有这个问题：
 implementation 'androidx.activity:activity-compose:1.9.0'
 implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.8.2'

**Comment by gangoogle** [comment]
错误日志：`java.lang.NoSuchMethodError: No virtual method setTagIfAbsent(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object; in class Landroidx/lifecycle/ViewModel; or its super classes (declaration of 'androidx.lifecycle.ViewModel' appears in /data/app/~~gCyitLC6T9ClcsfVv2CvNw==/com.fallout.tablewms-dhzuPVHVU6dnJY61s86SBg==/base.apk!classes18.dex)
13:59:27.568 19565-19565 System.err     com.fallout.tablewms     W  	at androidx.lifecycle.ScopeKt.scopeNetLife(Scope.kt:54)
13:59:27.568 19565-19565 System.err     com.fallout.tablewms     W  	at androidx.lifecycle.ScopeKt.scopeNetLife$default(Scope.kt:49)
13:59:27.568 19565-19565 System.err     com.fallout.tablewms     W  	at com.fallout.tablewms.ui.main.MainActivity.checkAppVersion$lambda$7(MainActivity.kt:212)
13:59:27.568 19565-19565 System.err     com.fallout.tablewms     W  	at com.fallout.tablewms.ui.main.MainActivity.$r8$lambda$d3BLUdiCCbUSuPh_4qwmcn0n1iY(Unknown Source:0)
13:59:27.568 19565-19565 System.err     com.fallout.tablewms     W  	at com.fallout.tablewms.ui.main.MainActivity$$ExternalSyntheticLambda3.invoke(D8$$SyntheticClass:0)
13:59:27.568 19565-19565 System.err     com.fallout.tablewms     W  	at com.drake.net.time.Interval$launch$1.invokeSuspend(Interval.kt:271)
13:59:27.569 19565-19565 System.err     com.fallout.tablewms     W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
13:59:27.569 19565-19565 System.err     com.fallout.tablewms     W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
13:59:27.569 19565-19565 System.err     com.fallout.tablewms     W  	at android.os.Handler.handleCallback(Handler.java:938)
13:59:27.569 19565-19565 System.err     com.fallout.tablewms     W  	at android.os.Handler.dispatchMessage(Handler.java:99)
13:59:27.569 19565-19565 System.err     com.fallout.tablewms     W  	at android.os.Looper.loop(Looper.java:223)
13:59:27.569 19565-19565 System.err     com.fallout.tablewms     W  	at android.app.ActivityThread.main(ActivityThread.java:7664)
13:59:27.569 19565-19565 System.err     com.fallout.tablewms     W  	at java.lang.reflect.Method.invoke(Native Method)
13:59:27.569 19565-19565 System.err     com.fallout.tablewms     W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
13:59:27.569 19565-19565 System.err     com.fallout.tablewms     W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by gangoogle** [comment]
![image](https://github.com/liangjingkanji/Net/assets/19320303/a8c8db8a-57a9-44ae-be6b-bfc42ed933e1)

**Comment by liangjingkanji** [comment]
折腾半天我升级后项目都没跑起来, @gangoogle 要不你fork仓库升级后发给我地址

**Comment by shanlinbawang** [comment]
期待尽快升级支持

**Comment by gangoogle** [comment]
> 折腾半天我升级后项目都没跑起来, @gangoogle 要不你fork仓库升级后发给我地址

ok 我整一下

**Comment by gangoogle** [comment]
@liangjingkanji 
[https://github.com/gangoogle/Net](https://github.com/gangoogle/Net)
升级gradle版本到8.3 以及Kotlin version到 1.9.20 编译通过了，现在爆红了 大佬有时间可以看看了 
![image](https://github.com/liangjingkanji/Net/assets/19320303/dbd4c8c3-d2d0-4d2f-8676-ddb76d87c488)

**Comment by cy000** [comment]
我也遇到这个问题了，期待解决

**Comment by cy000** [comment]
> ![image](https://private-user-images.githubusercontent.com/19320303/340942147-a8c8db8a-57a9-44ae-be6b-bfc42ed933e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODcwNTQsIm5iZiI6MTcyMzA4Njc1NCwicGF0aCI6Ii8xOTMyMDMwMy8zNDA5NDIxNDctYThjOGRiOGEtNTdhOS00NGFlLWJlNmItYmZjNDJlZDkzM2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAzMTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZWRiMjZmOGRjZjliYjg4M2NjNWJlNDAyOGFhMmNiNmQxZDE4N2E5MmQwMjEyOTU2NDcwYTA0MDc1OTMxOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.edjQn2dTNQmIvM14vmGgv6aqmZ9vq3XscED4tX-HE5g)

你解决了吗

**Comment by AdminQQZ** [comment]
我也遇到了

**Comment by cy000** [comment]
> 我也遇到了
我的处理方式，你可以参考一下
`fun ViewModel.scopeNetLife(
    dispatcher: CoroutineDispatcher = Dispatchers.Main,
    block: suspend CoroutineScope.() -> Unit
): NetCoroutineScope {
    val scope = NetCoroutineScope(dispatcher = dispatcher).launch(block)
    addCloseable(scope.toString(), scope)
    return getCloseable(scope.toString())?:NetCoroutineScope()
}`

**Comment by cy000** [comment]
> 我也遇到了



> 我也遇到这个问题了，期待解决



> 我也遇到了
我暂时这么解决的
![image](https://github.com/user-attachments/assets/e6b5c747-5463-49c4-885a-49e4224b28e3)

**Comment by liangjingkanji** [comment]
v3.7.0已经支持appcompat-v1.7, 但是一旦升级就不支持appcompat-v1.6了

由于无法实现兼容新旧版本, 只能发布v3.7.0了

**Comment by pokerfaceCmy** [comment]
你确定发布了3.7.0版本吗？
https://jitpack.io/com/github/liangjingkanji/Net/3.7.0/
```
File not found. Build Error
```

**Comment by liangjingkanji** [comment]
由于gradle升级导致无法远程仓库无法编译 耽搁了很久时间

目前已经通过升级依赖版本解决, 请升级最新版本即可  @pokerfaceCmy
