### ISSUE TITLE
可以实现流式传输吗

### ISSUE THREAD

**Issue by Clearpole** [liangjingkanji/Net#234]
如题

**Comment by liangjingkanji** [comment]
Net支持任何OkHttp的Api, 比如支持Body请求, 而Body支持流式传输

比如文档和Discussions都有提到如何实现 [使用文件流上传文件](https://github.com/liangjingkanji/Net/discussions/190)

如果还有不明白的搜索下 `OkHttp上传文件流`

**Comment by Clearpole** [comment]
好的，已解决👍
