### ISSUE TITLE
ktor适配请求

### ISSUE THREAD

**Issue by hmy65** [liangjingkanji/Net#237]
先说一句东哥牛逼不过分吧？

有没有可能吧okhttp换成ktor(cio)？

感谢东哥。

**Comment by liangjingkanji** [comment]
现在Net直接套OkHttp, 你让我改成 Net套Ktor然后Ktor套OkHttp? 这样目的是什么? 多写点代码吗?

另外出于回报而言也不会考虑除OkHttp以外的框架, 因为OkHttp生态完善, 换别的很多需求没有文章和案例

本开源框架是基于个人需求代码分享, 并没有商业目的, 大改框架去适配我压根不用的其他框架对我没任何意义, 但欢迎自己pr扩展

**Comment by liangjingkanji** [comment]
我很反感无意义的代码和人云亦云的"更好", 你自己能说得清楚这么提的含义吗?

**Comment by hmy65** [comment]
为了multiplatform，ktor用自带的cio engine, 不用okhttp的

**Comment by liangjingkanji** [comment]
并不会iOS, 无法适配多平台

**Comment by zhaoxiuyu** [comment]
协程 scope 能不能从 net 里面独立出来，单独封装一个库出来？
@liangjingkanji    祝你天天有奶茶喝。

**Comment by liangjingkanji** [comment]
> 协程 scope 能不能从 net 里面独立出来，单独封装一个库出来？ @liangjingkanji 祝你天天有奶茶喝。

这个协程是根据view和net封装的, 无法单独出来, 只能根据场景重写

设计上就没有需要分离的需求, 解耦会牺牲更多便利不值得
