### ISSUE TITLE
compose bate 分支，我使用源码方式依赖

### ISSUE THREAD

**Issue by AdminQQZ** [liangjingkanji/Net#238]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)
![QQ_1721806857282](https://github.com/user-attachments/assets/d7d83e0e-7862-48be-99f2-c97542237871)

## 版本
- Net:
- OkHttp: 4.10.0
- Android: compileSdk = "34"
- Gradle: 8.6
- Android Studio: 2023.3.1 Patch 1

**Comment by liangjingkanji** [comment]
compose的什么都没改, 没必要依赖

**Comment by liangjingkanji** [comment]
预计compose分支会删除掉所有和View相关的代码, 功能肯定会更少

可以理解为纯 协程+Okhttp网络框架了
