### ISSUE TITLE
转换json出现异常

### ISSUE THREAD

**Issue by AdminQQZ** [liangjingkanji/Net#239]

**Comment by AdminQQZ** [comment]
我发现 
![image](https://github.com/user-attachments/assets/f6ba59ef-ef5b-4baf-86c1-403e1954090a)
 这种写法，json转换出错了，控制台没有转换错误的信息

而下面这种写法能反馈错误信息
![image](https://github.com/user-attachments/assets/6f758568-5b31-402d-8ad0-a1e25516b938)

**Comment by AdminQQZ** [comment]
为什么解析上面的json会出错：


com.drake.net.exception.ConvertException: An unexpected error occurred in the converter http://192.168.137.1:8090/common/api/mobile/up/Login/Login ...(MainActivity.kt:41)
	at com.app.gw.MainActivity$fetchUserInfo$1$invokeSuspend$$inlined$Post$default$1.invokeSuspend(NetCoroutine.kt:231)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1012: Unexpected symbol 'a' in numeric literal at path: $.code
JSON input: ....."status":1,"prop":null,"code":"aa","create_time":null,"creat.....
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:596)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeNumericLiteral(AbstractJsonLexer.kt:654)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeInt(StreamingJsonDecoder.kt:297)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeIntElement(AbstractDecoder.kt:53)
	at com.app.ui.libdev.base.net.response.BaseResponseBean$$serializer.deserialize(BaseResponseBean.kt:8)
	at com.app.ui.libdev.base.net.response.BaseResponseBean$$serializer.deserialize(BaseResponseBean.kt:8)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
	at com.app.http.SerializationConverter.parseBody(SerializationConverter.kt:79)
	at com.app.http.SerializationConverter.onConvert(SerializationConverter.kt:50)
	at com.app.gw.MainActivity$fetchUserInfo$1$invokeSuspend$$inlined$Post$default$1.invokeSuspend(NetCoroutine.kt:224)
	... 8 more
Compat change id reported: 147798919; UID 10024; state: ENABLED

**Comment by AdminQQZ** [comment]
![image](https://github.com/user-attachments/assets/252068de-5315-47d5-81c0-284e7f6adc29)
是不是可以指定字段类型呀

**Comment by liangjingkanji** [comment]
我写了很多, 但是我最后决定删除, 你加群去问下吧

**Comment by AdminQQZ** [comment]
我把服务端的json data中的 code:"aa"改为 0 数字类型，真的能解析了！！！！这是解析器的问题吗。。。求解，mmm

**Comment by AdminQQZ** [comment]
这种写法是正常解析
![QQ_1723085855019](https://github.com/user-attachments/assets/d5d6968a-1d71-4a9c-88ee-22e0070d4164)

这种就报错了
![Uploading QQ_1723085917155.png…]()

**Comment by AdminQQZ** [comment]
![QQ_1723085917155](https://github.com/user-attachments/assets/a707c627-13c3-4dd1-b809-ef7d27f11c0f)

**Comment by liangjingkanji** [comment]
把报错的json和解析用的数据类发出来下

**Comment by AdminQQZ** [comment]
![QQ_1723086804361](https://github.com/user-attachments/assets/e6f1e0cd-f5be-4e4e-85ea-d66fc634d6ed)
发现是zhe'duan这段报错了

**Comment by AdminQQZ** [comment]
# json
{"code":200,"msg":"成功","data":{"account":"longhaiyang","account_type":3,"account_status":1,"org_id":"1","org_name":"中联区卫","property":1,"dept_name":"门诊外科","dept_code":"002","dept_prop":"A,B,C,D,E","dept_discipline":null,"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Ium-mea1t-a0iyIsInNvdXJzZSI6IjEiLCJhY2NvdW50IjoibG9uZ2hhaXlhbmciLCJvcmdpZCI6IjEiLCJ1c2VyVHlwZSI6IjIiLCJuYmYiOjE3MjMwODY3MzksImV4cCI6MTcyMzA5MzkzOSwiaWF0IjoxNzIzMDg2NzM5LCJpc3MiOiJJc3N1ZXIiLCJhdWQiOiJBdWRpZW5jZSJ9.Wh6K_gMBOTvheInd0o7zJNIS7phOtKvr3xarh81siDs","token_effective_period":1723093939,"role_id":null,"role_name":null,"is_super_admin":0,"org_code":"zlsoft","org_inner_code":"001","certificate_code":"9888","login_out_time":120,"login_product_id":null,"id":"98fc908d86f6a715","dept_id":"6a2f14d47fb4123a","name":"龙海洋","py_code":null,"sex":0.0,"nation_code":null,"healthcare_code":null,"edu_code":null,"staff_brsdate":null,"staff_idno":null,"tel":null,"mobile":"","email":null,"post_code":null,"summary":null,"speciality":null,"status":1.0,"prop":null,"code":"aa","create_time":null,"create_user":null,"update_time":null,"update_user":null,"grade_code":null,"reference_id":null,"face_photo":null,"sign_photo":null,"licence_code":null,"valid_certifi_type":null,"valid_certifi_no":null,"practice_area":null,"practice_certifi_code":null,"place_of_reg":null,"validsign_of_prescription":null,"start_of_practice":"0001-01-01 00:00:00","end_of_practice":"0001-01-01 00:00:00","last_pwd_date":"2022-12-14 18:05:10","sno":0,"show_introduce":false,"mobile_token":"5d0eca5e9f2648cabbe5b47a61484312"},"timestamp":0,"errormessage":null}


解析类
`/**
 * 基础响应类-对应着服务端接口来修改
 */
@Serializable
class BaseResponseBean<T> {

    /** 响应状态码，默认为0 */
    var code: Int = -1


    /** 响应数据，类型为泛型T，可为空*/
    var data: T? = null

    /** 响应信息，默认为空 */
    var msg: String? = null

    /**
     * 公共接口 状态码-0表示成功 ，其他则是失败
     */
    val isOk: Boolean get() = code == 200
}

`


`@Serializable
data class UserDataBean(
    // 映射
    @SerialName("data")
    val data: Datas
) {

    fun toConvertProtoType(): UserBeanProto? {
        return UserBeanProto.newBuilder().setData(
            dataProto {
                // 数据转换赋值
//                chatToken = this@UserDataBean.chatToken
//                session = this@UserDataBean.session
//                userId = this@UserDataBean.userId

                if (this@UserDataBean.data.id?.isNotEmpty() == true) {
//                    user = UserProto.newBuilder()
//                        .setCity(this@UserDataBean.user.city)
//                        .setArea(this@UserDataBean.user.area)
//                        .setId(this@UserDataBean.user.id)
//                        .setNickname(this@UserDataBean.user.nickname)
//                        .setIcon(this@UserDataBean.user.icon ?: "")
//                        .setApp(this@UserDataBean.user.app)
//                        .build()
                } else {
                    throw NullPointerException("user.id is null")
                }
            }
        ).build()
    }

    // {"code":200,"msg":"成功","data":{"account":"longhaiyang","account_type":3,"account_status":1,"org_id":"1","org_name":"中联区卫","property":1,"dept_name":"门诊外科","dept_code":"002","dept_prop":"A,B,C,D,E","dept_discipline":null,"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Ium-mea1t-a0iyIsInNvdXJzZSI6IjEiLCJhY2NvdW50IjoibG9uZ2hhaXlhbmciLCJvcmdpZCI6IjEiLCJ1c2VyVHlwZSI6IjIiLCJuYmYiOjE3MjMwMjU3NjAsImV4cCI6MTcyMzAzMjk2MCwiaWF0IjoxNzIzMDI1NzYwLCJpc3MiOiJJc3N1ZXIiLCJhdWQiOiJBdWRpZW5jZSJ9.0mMWgeueuv71YbgL4m0tlFW4dEeFCVvSzLZO-fKsBPc","token_effective_period":1723032960,"role_id":null,"role_name":null,"is_super_admin":0,"org_code":"zlsoft","org_inner_code":"001","certificate_code":"9888","login_out_time":120,"login_product_id":null,"id":"98fc908d86f6a715","dept_id":"6a2f14d47fb4123a","name":"龙海洋","py_code":null,"sex":0.0,"nation_code":null,"healthcare_code":null,"edu_code":null,"staff_brsdate":null,"staff_idno":null,"tel":null,"mobile":"","email":null,"post_code":null,"summary":null,"speciality":null,"status":1.0,"prop":null,"code":"aa","create_time":null,"create_user":null,"update_time":null,"update_user":null,"grade_code":null,"reference_id":null,"face_photo":null,"sign_photo":null,"licence_code":null,"valid_certifi_type":null,"valid_certifi_no":null,"practice_area":null,"practice_certifi_code":null,"place_of_reg":null,"validsign_of_prescription":null,"start_of_practice":"0001-01-01 00:00:00","end_of_practice":"0001-01-01 00:00:00","last_pwd_date":"2022-12-14 18:05:10","sno":0,"show_introduce":false,"mobile_token":"404b2913d2784d61b3fdf1ae593382fc"},"timestamp":0,"errormessage":null}
    @Serializable()
    data class Datas(
        val account: String?,
        val account_status: String?,
        val account_type: String?,
        val certificate_code: String?,
        val code: String?,
        val create_time: String?,
        val create_user: String?,
        val dept_code: String?,
        val dept_discipline: String?,
        val dept_id: String?,
        val dept_name: String?,
        val dept_prop: String?,
        val edu_code: String?,
        val email: String?,
        val end_of_practice: String?,
        val face_photo: String?,
        val grade_code: String?,
        val healthcare_code: String?,
        val id: String?,
        val is_super_admin: String?,
        val last_pwd_date: String?,
        val licence_code: String?,
        val login_out_time: String?,
        val login_product_id: String?,
        val mobile: String?,
        val mobile_token: String?,
        val name: String?,
        val nation_code: String?,
        val org_code: String?,
        val org_id: String?,
        val org_inner_code: String?,
        val org_name: String?,
        val place_of_reg: String?,
        val post_code: String?,
        val practice_area: String?,
        val practice_certifi_code: String?,
        val prop: String?,
        val `property`: String?,
        val py_code: String?,
        val reference_id: String?,
        val role_id: String?,
        val role_name: String?,
        val sex: Double?,
        val show_introduce: Boolean?,
        val sign_photo: String?,
        val sno: String?,
        val speciality: String?,
        val staff_brsdate: String?,
        val staff_idno: String?,
        val start_of_practice: String?,
        val status: Double?,
        val summary: String?,
        val tel: String?,
        val token: String?,
        val token_effective_period: String?,
        val update_time: String?,
        val update_user: String?,
        val valid_certifi_no: String?,
        val valid_certifi_type: String?,
        val validsign_of_prescription: String?,
    )

}


`
