### ISSUE TITLE
建议大家都别用，我随口说了一句，被骂惨了。。。

### ISSUE THREAD

**Issue by liuya891012** [liangjingkanji/Net#240]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
请勿提和本开源项目无关的内容

**Comment by liuya891012** [comment]
好的，东哥
