### ISSUE TITLE
3.7.0无法下载

### ISSUE THREAD

**Issue by AdminQQZ** [liangjingkanji/Net#242]
### 期望行为
正常下载
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图
![image](https://github.com/user-attachments/assets/9972d2ea-dbf5-44eb-ba9e-917de8c2b3f5)

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by AdminQQZ** [comment]
东子，你在哪

**Comment by AdminQQZ** [comment]
急急急，

**Comment by liangjingkanji** [comment]
远程仓库看起来不支持最新的gradle, 我可能得更换远程仓库厂商了

目前只能你aar依赖了

**Comment by ysy950803** [comment]
不打算解决了吗？aar在哪里？
