### ISSUE TITLE
协程上下文为什么传的EmptyCoroutineContext

### ISSUE THREAD

**Issue by caihuanjian** [liangjingkanji/Net#244]
## 问题描述
看不懂源码啊，AndroidScope，NetCoroutineScope的launch方法为什么传EmptyCoroutineContext，那原来作用域的context不是被忽略了吗，是我认知有问题吗，谁能解答一下~

**Comment by liangjingkanji** [comment]
`launch`默认就是EmptyCoroutineContext, 第一次launch也不存在`原来的作用域`
