### ISSUE TITLE
如何先从缓存读取，读取成功就不请求网络，读取失败或缓存过期就请求网络

### ISSUE THREAD

**Issue by Gxaasec** [liangjingkanji/Net#245]
## 问题描述
看了缓存文档 https://liangjingkanji.github.io/Net/cache.html#_3 
想实现一个效果，就是先从缓存读取，读取成功就不请求网络，读取失败或缓存过期就请求网络，应该如何配置呢，把强转缓存模式试了个遍都没成功，都会请求网络；

### 期望行为
希望先从缓存读取，读取成功就不请求网络，读取失败或缓存过期就请求网络
## 如何复现
demo任意接口
> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间
谢谢大佬
## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
章节5 [预览(缓存+网络)](https://liangjingkanji.github.io/Net/cache.html#_5) 不就是你的需求吗?
