### ISSUE TITLE
麻烦适配下 高版本的lifecycleViewmodelKtx

### ISSUE THREAD

**Issue by lee-you** [liangjingkanji/Net#246]
## 问题描述
使用 lifecycleViewmodelKtx 2.8.6 版本崩溃
java.lang.NoSuchMethodError: No virtual method setTagIfAbsent(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object; in class Landroidx/lifecycle/ViewModel; or its super classes (declaration of 'androidx.lifecycle.ViewModel' appears in /data/app/~~QqYieA7YCoZYU2p8qjEepQ==/com.smart.newvideo1-6KyLt3VxLlzYEHtPFT9pmw==/base.apk)

at androidx.lifecycle.ScopeKt.scopeNetLife(Scope.kt:54)

把lifecycleViewmodelKtx版本 降低到 2.6.2版本 就没崩溃了

### 期望行为
适配 高版本的 viewmodel 
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:2.6.4
- OkHttp: 4.11.0
- Android:13
- Gradle: 8.7
- Android Studio:2024.1.2

**Comment by liangjingkanji** [comment]
我早就适配了但是要求高版本gradle, 然后jitpack好像不支持高版本gradle打包

我尽快发布新版的远程依赖, 目前只能手动aar依赖了

**Comment by liangjingkanji** [comment]
由于gradle升级导致无法远程仓库无法编译 耽搁了很久时间

目前已经通过升级依赖版本解决, 请升级最新版本即可
