### ISSUE TITLE
viewModel中多次请求没返回数据

### ISSUE THREAD

**Issue by HarrisonShen** [liangjingkanji/Net#28]
比如在viewmodel中请求fetchUserInfo1和fetchUserInfo2只能返回fetchUserInfo1的数据第二个请求没请求,使用scope请求却可以返回2次的数据

fun fetchUserInfo1()  {
         scopeNetLife {
             Get<String>(Api.userTokenAUth1).await()
        }
    }

fun fetchUserInfo2()  {
         scopeNetLife {
             Get<String>(Api.userTokenAUth2).await()
        }
    }

**Comment by liangjingkanji** [comment]
你大括号多写了一层， 导致整个函数压根没有声明返回值

**Comment by HarrisonShen** [comment]
> 你大括号多写了一层， 导致整个函数压根没有声明返回值

这样写不是对的吗 函数里面括号，网络请求括号
换成 这样也不行啊 你这边能测试一下吗
fun fetchUserInfo1() =
         scopeNetLife {
             Get<String>(Api.userTokenAUth1).await()
        }

    fun fetchUserInfo2() =
        scopeNetLife {
            Get<String>(Api.userTokenAUth2).await()
        }

**Comment by HarrisonShen** [comment]
> 你大括号多写了一层， 导致整个函数压根没有声明返回值

这样写不是对的吗 函数里面括号，网络请求括号
换成 这样也不行啊 你这边能测试一下吗
fun fetchUserInfo1() =
         scopeNetLife {
             Get<String>(Api.userTokenAUth1).await()
        }

    fun fetchUserInfo2() =
        scopeNetLife {
            Get<String>(Api.userTokenAUth2).await()
        }

**Comment by liangjingkanji** [comment]
协程作用域是异步的不能直接封装到函数中然后返回数据的, 数据是异步的, 但是你的这个函数是同步的. 这是错误写法

你可以查看
1. Demo中的[ViewModel请求](https://github.com/liangjingkanji/Net/blob/master/sample/src/main/java/com/drake/net/sample/ui/fragment/ViewModelRequestFragment.kt)
2. 使用文档中的[ViewModel](https://liangjingkanji.github.io/Net/view-model.html)

```kotlin
fun fetchUserInfo2() =
    scopeNetLife {
        liveData = Get<String>(Api.userTokenAUth2).await()
 }
```

**Comment by HarrisonShen** [comment]
> 协程作用域是异步的不能直接封装到函数中然后返回数据的, 数据是异步的, 但是你的这个函数是同步的. 这是错误写法
> 
> 你可以查看
> 
> 1. Demo中的[ViewModel](https://github.com/liangjingkanji/Net/blob/master/sample/src/main/java/com/drake/net/sample/ui/fragment/ViewModelRequestFragment.kt)
> 2. 使用文档中的[ViewModel](https://liangjingkanji.github.io/Net/view-model.html)
> 
> 你应当创建一个liveData来接受返回的数据, 然后在Activity中观察liveData
> 
> ```kotlin
> fun fetchUserInfo2() =
>     scopeNetLife {
>         liveData = Get<String>(Api.userTokenAUth2).await()
>  }
> ```
> 
> 或者只封装请求动作不封装作用域
> 
> ```kotlin
> fun CoroutineScope.fetchUserInfo2() = Get<String>(Api.userTokenAUth2)
> ```

我是这样写的
class UserViewModel : ViewModel() {

    // 用户信息
    var userInfo1: MutableLiveData<String> = MutableLiveData()
    var userInfo2: MutableLiveData<String> = MutableLiveData()

    fun fetchUserInfo1() = scopeNetLife {
            userInfo1.value = Get<String>(Api.userTokenAUth1).await()
        }

    fun fetchUserInfo2() = scopeNetLife {
             userInfo2.value = Get<String>(Api.userTokenAUth2).await()
        }
}

请求2次 viewModel.fetchUserInfo1()
        viewModel.fetchUserInfo2()
但是只请求了第一次，写法不对吗

**Comment by liangjingkanji** [comment]
1. 首先你先百分百确定只执行了一次请求
2. 给我看下你的调用位置写法
3. 在ViewModel中使用`scopeNetLife`, 如果ViewModel被销毁其网络请求会自动取消. 这点请你先知道
4. 如果觉得问题沟通不够及时可以加群实时沟通

**Comment by HarrisonShen** [comment]
> 1. 首先你先百分百确定只执行了一次请求
> 2. 给我看下你的调用位置写法
> 3. 在ViewModel中使用`scopeNetLife`, 如果ViewModel被销毁其网络请求会自动取消. 这点请你先知道
> 4. 如果觉得问题沟通不够及时可以加群实时沟通

可以确定只执行了一次请求，改用scope就执行2次,scopeNetLife就执行第一次的网络请求
class MainActivity : MyBaseActivity() {
  
    private lateinit var viewModel: UserViewModel

    override fun getLayoutID(): Int {
        return R.layout.activity_main
    }

    override fun initViewModel() {
        viewModel = getViewModel()
        viewModel.fetchUserInfo1()
        viewModel.fetchUserInfo2()
    }
ViewModel没有销毁
另外怎么加群有群号吗
而且我试了你demo中请求二个接口也只请求了1个
 // 动作开始拉取服务器数据
        btn_fetch_userinfo.setOnClickListener {
            userViewModel.fetchUserInfo()
            userViewModel.fetchUserInfo2()
        }
  /**
     * 拉取用户信息, 会自动通知页面更新, 同时页面销毁会自动取消网络请求
     */
    fun fetchUserInfo() = scopeNetLife {
        userInfo.value = Get<String>("api").await()
    }
    fun fetchUserInfo2() = scopeNetLife {
        userInfo2.value = Get<String>("api").await()
    }

**Comment by liangjingkanji** [comment]
<a href="https://jq.qq.com/?_wv=1027&k=vWsXSNBJ"><img src="https://img.shields.io/badge/QQ群-752854893-blue"/></a>
如果有问题需要马上解决可以直接点击按钮加群问.  README也有QQ群徽章
这个问题我看的确像是有问题.  复用了被取消的作用域

**Comment by HarrisonShen** [comment]
> [![](https://camo.githubusercontent.com/9385e39c7e3118eabc3ef9a796677b6eb428835b14479ef1e99db66d89e9b60b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5151e7bea42d3735323835343839332d626c7565)](https://jq.qq.com/?_wv=1027&k=vWsXSNBJ)
> 如果有问题需要马上解决可以直接点击按钮加群问. README也有QQ群徽章
> 这个问题我看的确像是有问题. 复用了被取消的作用域

已经添加qq群麻烦尽快解决下 准备用这个框架呢现在用的是3.x的okhttp版本

**Comment by liangjingkanji** [comment]
修复在
```groovy
// Net
implementation 'com.github.liangjingkanji:Net:3.0.11'
```
