### ISSUE TITLE
this.mediaType = JSON，修改mediaType 失败

### ISSUE THREAD

**Issue by masite** [liangjingkanji/Net#29]
Post<String>(""){
                this.mediaType = JSON
            }.await()

请求后，接口还是按Content-Type: application/x-www-form-urlencoded 这样。

何解？

**Comment by masite** [comment]
加个 json(JSONObject())  就生效了，不知道咋回事，说不清

**Comment by liangjingkanji** [comment]
mediaType设置的是Multipart参数形式的类型.  但是Json不属于Multipart
