### ISSUE TITLE
生命周期关联失败

### ISSUE THREAD

**Issue by linyingfa** [liangjingkanji/Net#31]
binding.tvContent.postDelayed({
            scopeNetLife(Lifecycle.Event.ON_DESTROY) {
                val json = Get<String>("https://www.wanandroid.com/article/list/0/json").await()
                val a12 = Looper.myLooper() == Looper.getMainLooper()
                LoggerUtils.i(" TM.530530530---->$a12---json>$json")
            }.catch { }.finally { }
        }, 5000)

请问，这样，activitiy关闭了，为什么5s后，还会执行这个请求

**Comment by liangjingkanji** [comment]
postDelayed会导致内存泄漏. 导致在activity已经执行onDestroy后依然会执行{}的内容. 从而导致会继续发起网络请求. 

但是不会继续执行onDestroy. 而`scope*Life`等函数是在onDestroy时自动取消. 所以故也不会自动取消网络请求

postDelayed等操作慎用. 你可以在scope里面使用`delay`来进行延时

**Comment by liangjingkanji** [comment]
建议替换代码

```kotlin
scopeNetLife {
  delay(5000)
  val json = Get("https://www.wanandroid.com/article/list/0/json").await()
}
```

**Comment by linyingfa** [comment]
好的👌🏻，谢谢





------------------ 原始邮件 ------------------
发件人: 劉強東 ***@***.***&gt;
发送时间: 2021年7月7日 16:31
收件人: liangjingkanji/Net ***@***.***&gt;
抄送: 530 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[liangjingkanji/Net] 生命周期关联失败 (#31)





 
建议替换代码
 scopeNetLife {   delay(5000)   val json = Get("https://www.wanandroid.com/article/list/0/json").await() }
