### ISSUE TITLE
关于分层设计

### ISSUE THREAD

**Issue by Berial** [liangjingkanji/Net#38]
我想把具体请求放在一个或多个Repo里，但是请求方法都是CoroutineScope.xxxx。我现在是重新封装了一下post/get方法：
```
suspend inline fun <reified M> post(
    path: String,
    tag: Any? = null,
    noinline block: (BodyRequest.() -> Unit)? = null
): Deferred<M> = coroutineScope {
    async(Dispatchers.IO + SupervisorJob()) {
        BodyRequest().apply {
            setPath(path)
            method = Method.POST
            setGroup(coroutineContext[CoroutineExceptionHandler])
            setTag(tag)
            block?.invoke(this)
        }.execute()
    }
}
```

某Repo：
```
suspend fun fetchXxxxxx() = post(Api.xxxxx) {
    param("xxx", "xxx")
}
```

某ViewModel:
```
fun xxxx() {
    scopeNetLife {
        val result = repo.fetchXxxxxx().await()
    }
}
```

请问有更好的实现方法吗？而且例如scopeDialog等作用域只能在Activity/Fragment中使用，在分层架构中也无法用到。

**Comment by liangjingkanji** [comment]
作用域和请求动作本身是分离的, 作用域负责的是生命周期和自动化的流程. 作用域本身没必要写在ViewModel中

某Repo: 使用扩展函数即可
```
fun Coroutine.fetchXxxxxx() = post(Api.xxxxx) {
    param("xxx", "xxx")
}
```

当然如果你想让ViewModel自动处理生命周期可以阅读 [ViewModel作用域文档](https://liangjingkanji.github.io/Net/view-model/)

至于scopeDialog需要Activity, 你可以使用你的全局当前Activity. 或者只在ViewModel中封装请求动作`post/get`, 然后再Activity中使用`scopeDialog`...


> 封装代码首先考虑扩展性和是否值得, 不要像套公式一样为了封装而封装

**Comment by Berial** [comment]
好的，谢谢。

**Comment by microzhang715** [comment]
没有合理的分层和设计，请求逻辑和UI混在一起，大型项目后续维护成本巨高，但是小项目一把梭也无妨
