### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by hanyechun** [liangjingkanji/Net#39]
上传文件，接口日志 Not support this type multipart/form-data; boundary=49e67671-b4fc-461a-9fda-78cac66a95a0，然后就是超市异常。这可能是什么原因导致的呢。

**Comment by liangjingkanji** [comment]
`multipart/form-data`是通用的文件上传格式, 是你们后端开发问题 

你可以尝试创建原始RequestBody

```
scopeNetLife {
   Get<String>("upload"){
      body = file.toRequestBody()
   }.await()
}
```

**Comment by hanyechun** [comment]
> 你设置下OkHttpClient的超时设置试试
> 
> ```
> scopeNetLife {
>     Post<String>("upload") {
>         param("file", assetsFile())
>         setClient { 
>             readTimeout(3, TimeUnit.MINUTES)
>             writeTimeout(3, TimeUnit.MINUTES)
>         }
>     }.await()
> }
> ```

我在application中配置了超时，请求V/OKPRFL_b1ztx2m_RQB: Not support this type multipart/form-data; boundary=6645320d-f6f2-48dc-8023-5eb6f80a1969，调用接口之后日志not support然后就会超时 com.drake.net.exception.NetSocketTimeoutException: failed to connect to /************* (port 8080) from /************ (port 43236) after 15000ms (******************************************

**Comment by hanyechun** [comment]
val data = Post<BaseModel<FileModel>>("$NET_HOST$UPLOAD_FILE") {
                    param("file", File(it.realPath))
                }.await().data
这是我的上传接口代码

**Comment by liangjingkanji** [comment]
错误信息截图发我，里面包含子异常

**Comment by hanyechun** [comment]
![image](https://user-images.githubusercontent.com/20107312/130608342-d7808891-ec9c-4fb6-a39e-93fe60a3fd86.png)

**Comment by hanyechun** [comment]
![image](https://user-images.githubusercontent.com/20107312/130608522-df55fa0d-2acd-4ff7-b854-509b5b0a4b21.png)
![image](https://user-images.githubusercontent.com/20107312/130608591-2f42a412-ef18-4092-b195-7ecb6ba72bad.png)

**Comment by liangjingkanji** [comment]
```
Not support this type multipart/form-data; boundary=5070c343-d275-40fe-a7ec-46d2c016cf29
```
这是不支持日志输出类型

你这个确定服务器能连接上吗? 你试下接口测试工具请求下

**Comment by hanyechun** [comment]
> ```
> Not support this type multipart/form-data; boundary=5070c343-d275-40fe-a7ec-46d2c016cf29
> ```
> 
> 这是不支持日志输出类型
> 
> 你这个确定服务器能连接上吗? 你试下接口测试工具请求下

服务器我用postman是可以的，上传也没有问题

**Comment by hanyechun** [comment]
> ```
> Not support this type multipart/form-data; boundary=5070c343-d275-40fe-a7ec-46d2c016cf29
> ```
> 
> 这是不支持日志输出类型
> 
> 你这个确定服务器能连接上吗? 你试下接口测试工具请求下

抱歉，postman在我电脑上连接的是内网，是我文件地址有偏差。

**Comment by liangjingkanji** [comment]
没问题就行 ☺️
