### ISSUE TITLE
很好的网络请求框架，用在新项目里了。

### ISSUE THREAD

**Issue by MoonandMind** [liangjingkanji/Net#4]

**Comment by liangjingkanji** [comment]
有问题可以反馈,  如果有任何使用上的问题可以点击图标加群

**Comment by zhaoxiuyu** [comment]
@liangjingkanji  狗东，能不能把 net 里面的 scope 分离出来 单独搞个库。

**Comment by liangjingkanji** [comment]
@zhaoxiuyu 不提供另外的请求方式, 而且使用的内联函数也无法分离

**Comment by LiWeiQiangAndroid** [comment]
没java版了吧

**Comment by liangjingkanji** [comment]
> 没java版了吧

本框架以协程为核心, Java不支持协程, 而且既然都选择了Java我觉得不用去考虑什么效率问题了, 吃蛋糕还喝什么零糖可乐

如果只是项目中存在Java代码那可以通过编写桥接用的kt函数支持

**Comment by artillerymans** [comment]
提个需求:支持一下多平台类似Compose Desktop上也能直接用就好了

**Comment by breakadmin** [comment]
HttpFailureException

**Comment by liangjingkanji** [comment]
> @liangjingkanji 跟平台没有关系,只是业务层的话,存kotlin能在JVM下跑的,不依赖android特有的包我觉得就够了

不依赖kotlin的话那就使用`ktor`吧, okhttp依赖于jvm, 而net依赖于android, 本身框架就是功能越完善就越局限于平台
