### ISSUE TITLE
不能在使用mvvm设计模式的时候使用框架带的dialog

### ISSUE THREAD

**Issue by woaimi520** [liangjingkanji/Net#46]
发现在初始化的时候配置默认的loading 在fragment ->viewmode 中请求的时候没有看到loading
      setDialogFactory { // 全局加载对话框
                ProgressDialog(it).apply {
                    setMessage("我是全局自定义的加载对话框...")
                }
            }

**Comment by woaimi520** [comment]
文档有看 大佬这个在mvvm中的使用场景 封装一个在view层发起的请求 也能弹出loading 后续也可以封装一个工具类吗

**Comment by liangjingkanji** [comment]
你不要封装scope就行了, 网络请求封装动作`Post/Get`即可.  而且没有Activity引用无法显示Dialog
