### ISSUE TITLE
关于特殊结构解析问题

### ISSUE THREAD

**Issue by greadking** [liangjingkanji/Net#47]
{
    "code":0,
    "msg":"请求成功",
    "data":”“
}
data为String  按照[https://liangjingkanji.github.io/Net/convert-special/](url)配置
Get<String>("api").await() 这里拿到的是 整个响应而不是响应中的data 字段 
查看源码 发现return NetConverter.onConvert<R>(succeed, response) 成功return了 就没有往下看 
只能这样写Post<BaseBean<String>> ...  .data 去获取
@liangjingkanji 作者大人  有没有空解一下

**Comment by liangjingkanji** [comment]
![image](https://user-images.githubusercontent.com/21078112/140026375-359a65ab-fb62-4e09-802d-3420b30b9b58.png)

**Comment by greadking** [comment]
这里我是有看到的  
接口对象
open class BaseBean<T>(
    var message: String = "net no message content",
    var code: Int = 0,
    var data: T? = null
)


转换器
 override fun <R> String.parseBody(succeed: Type): R? {
        val data = JSONObject(this).getString("data")
        return gson.fromJson(data, succeed)
    }

接口调用写法
Post<String>(”api“) {}.await() 拿到的是 BaseBean的json  而不是BaseBean中的data的string  
debug 发现  return NetConverter.onConvert<R>(succeed, response) 直接从succeed === String::class.java -> response.body?.string() as R return出去了 没有走 bodyString.parseBody<R>(succeed) 方法

**Comment by greadking** [comment]
根据代码判断 当泛型为 String  ByteString Response File 等对象时  都是直接解析的 不会去走
override fun String.parseBody(succeed: Type): R? {
val data = JSONObject(this).getString("data")
return gson.fromJson(data, succeed)
这里的方法

**Comment by liangjingkanji** [comment]
是的. 你可以自己在自定义的转换器上顶部拦截. 我也考虑过是否让成功才允许返回String. 但是那样就要将异常对象放到默认的转换器中处理, 感觉不太好. 限制住了
