### ISSUE TITLE
关于发起请求时 返回类型 定义为泛型的问题

### ISSUE THREAD

**Issue by greadking** [liangjingkanji/Net#48]
![Dingtalk_20211120091743](https://user-images.githubusercontent.com/26962322/142709192-5322be00-d23d-4dd8-82e1-2210325a6d48.jpg)
![Dingtalk_20211120091802](https://user-images.githubusercontent.com/26962322/142709194-1ef99a5d-58aa-4ec2-a72a-5659d0de79a2.jpg)
然后看见了这个错：UnsupportedOperationException: This function has a reified type parameter and thus can only be inlined at compilation time, not called directly.
我对kotlin的理解 还不够深刻  网上找了 也没有找到 解决方案 
作者大人有时间的话帮忙解答一下吗 蟹蟹

**Comment by greadking** [comment]
如果想要实现在 Get<E> {}.await  E  由外部传入进来   有没有思路

**Comment by liangjingkanji** [comment]
完全可以
```kotlin
GET<String>()

private inline fun <reified M> GET() {
    scopeNetLife {
        val response = Get<M>("api").await()
    }
}
```
