### ISSUE TITLE
关于PullRefreshFragment 下拉刷新加载更多的问题

### ISSUE THREAD

**Issue by greadking** [liangjingkanji/Net#49]
activity中使用 beginTransaction().func().commit()添加fragment 
![143796356-5757dcd3-231a-4e7e-b2ef-17d4157a90d2](https://user-images.githubusercontent.com/26962322/143799306-e3195eb4-ba4b-4983-9fe2-84788d96dab6.jpg)

但是加载出来的数据有些问题  需要主动触发 下拉刷新 而且上面会有留白
![Screenshot_2021-11-29-09-21-26-125_com gk world comprehensive](https://user-images.githubusercontent.com/26962322/143796495-b9996df1-8c3c-4480-948e-ba885e3e76fa.jpg)
作者大人可否帮忙分析一哈

**Comment by greadking** [comment]
获取数据的写法与dome 中一样
binding.page.onRefresh {
    scope {
        val data = Get<List<UserModelBean>>("list") {
            param("page", index)
        }.await()
        addData(data) {
            index < 100 // 最多加载100个
        }
    }

**Comment by liangjingkanji** [comment]
我看下

**Comment by liangjingkanji** [comment]
你只是声明并没有调用刷新函数

正确示例如下
```
binding.page.onRefresh {

}.showLoading() // 使用缺省页


binding.page.onRefresh {

}.autoRefresh() // 触发下拉刷新
```

**Comment by greadking** [comment]
有加的 少copy了一行 不好意思

**Comment by liangjingkanji** [comment]
留白问题没看出来. 你能不能在fork仓库并且在demo上复现下, 我好看问题

**Comment by liangjingkanji** [comment]
- 你的`binding.page.onRefresh`是声明在Fragment的哪个生命周期函数中?
- 你的`addFragment`函数具体实现是什么

**Comment by liangjingkanji** [comment]
另外你有暴露项目包名, 可以重新截图再次编辑内容

**Comment by greadking** [comment]
<img width="775" alt="B98E6FA6-BD8E-484d-AB5E-15B97B4EBE74" src="https://user-images.githubusercontent.com/26962322/143798141-bfe0f56a-61a1-4114-9b70-afcc0e14840e.png">
![Dingtalk_20211129100446](https://user-images.githubusercontent.com/26962322/143798143-5113e0fd-8cbc-45e3-8367-ea999abc0973.jpg)
好的蟹蟹 老师指教  fork仓库 要稍等一下

**Comment by greadking** [comment]
![Uploading Dingtalk_20211129100446.jpg…]()

**Comment by greadking** [comment]
![Dingtalk_20211129100446](https://user-images.githubusercontent.com/26962322/143798283-45b4fff5-35c7-4c3e-be3b-2680ec971e6f.jpg)

**Comment by greadking** [comment]
问题找到了  是我不够细心api没有看完成
 // 初始化SmartRefreshLayout, 这是自动下拉刷新和上拉加载采用的第三方库  [https://github.com/scwang90/SmartRefreshLayout/tree/master] V2版本
        SmartRefreshLayout.setDefaultRefreshHeaderCreator { context, _ ->
            MaterialHeader(context)
        }

        SmartRefreshLayout.setDefaultRefreshFooterCreator { context, _ ->
            ClassicsFooter(context)
        }

这俩没有加

**Comment by liangjingkanji** [comment]
那你怎么可以主动触发下拉刷新?

**Comment by greadking** [comment]
> 那你怎么可以主动触发下拉刷新?

没有设置的时候是可以的  就是上面会有留白

**Comment by liangjingkanji** [comment]
明白了
