### ISSUE TITLE
违法广告法

### ISSUE THREAD

**Issue by cyixlq** [liangjingkanji/Net#5]
des违法广告法😂

**Comment by liangjingkanji** [comment]
那可以推荐个更好的, 我删掉, 哈哈

**Comment by lhj1079947827** [comment]
使用说明打不开

**Comment by liangjingkanji** [comment]
> 使用说明打不开

我使用的是GitHub部署的文档, 理论上是不存在打不开的吧. 你可以试着开个代理或者切换下DNS. 如果还是无法打开请截图发我看下错误信息. 我再解决

**Comment by liangjingkanji** [comment]
> 使用说明打不开

README已经添加一个备用的文档访问地址.  [备用访问](https://coding-pages-bucket-3558162-8706000-16642-587704-1252757332.cos-website.ap-shanghai.myqcloud.com/)

**Comment by lhj1079947827** [comment]
可以访问了。
