### ISSUE TITLE
怎么方便的获取响应headers

### ISSUE THREAD

**Issue by BLOODMAGEBURT** [liangjingkanji/Net#53]
使用自定义的GsonConverter之后，await()返回的是Response的body的内容，怎么能获取到headers呢
![image](https://user-images.githubusercontent.com/16059706/147731560-321d15a9-f491-428e-9192-75e12b14719f.png)

**Comment by liangjingkanji** [comment]
await返回的是你写的泛型

```kotlin
val response: Model = Post<Model>.await()
```

如果你想要获取数据同时还获得headers你就只能返回Response
```kotlin
val response:Response = Post<Response>.await()
reponse.headers()
```

**Comment by BLOODMAGEBURT** [comment]
明白了，谢谢
