### ISSUE TITLE
使用inline reified封装请求函数导致崩溃

### ISSUE THREAD

**Issue by greadking** [liangjingkanji/Net#54]
如下图
<img width="701" alt="44D70AE9-33A7-48a8-B8B0-AE8EE8E8AB16" src="https://user-images.githubusercontent.com/26962322/148312270-d12af248-f0db-4861-bdcc-238ef727465c.png">
我是想要实现一个高服用的列表fragment 返回值类型需要再外部定义 于是使用inline reified的方式 但是会
报错.UnsupportedOperationException: This function has a reified type parameter and thus can only be inlined at compilation time, not called directly.
没有找到解决方案 作者大人可以看下吗

**Comment by greadking** [comment]
我现在这样处理的
但是总是多了一步
![Dingtalk_20220106093036](https://user-images.githubusercontent.com/26962322/148313606-1998f0ac-4b2d-444d-9d64-78e234380314.jpg)

**Comment by greadking** [comment]
现在是加了一层 gson  解决的 
![Dingtalk_20220106094933](https://user-images.githubusercontent.com/26962322/148315195-73eae50b-2be3-4102-a1d8-149db25a4d76.jpg)

**Comment by liangjingkanji** [comment]
理论上使用inline封装inline函数不存在问题, 你尝试升级kotlin插件试下
如果还不行fork仓库给我看下代码效果

**Comment by greadking** [comment]
> 理论上使用inline封装inline函数不存在问题, 你尝试升级kotlin插件试下 如果还不行fork仓库给我看下代码效果

https://github.com/greadking/Net.git  麻烦东哥了

**Comment by liangjingkanji** [comment]
这个问题是Get内部使用了`typeOf`函数抛出的. kotlin不允许在lambda中使用该函数. 所以你这种封装不允许. 因为onRefresh就属于lambda

**Comment by greadking** [comment]
蟹蟹强哥，我现在加了一步 解决了这个问题 但总是有些别扭 希望随着对kotlin的深入学习可以解决吧
![Dingtalk_20220106151602](https://user-images.githubusercontent.com/26962322/148344102-19511ca7-f281-4690-9418-bb97ea45a78a.jpg)

**Comment by liangjingkanji** [comment]
这个问题属于官方未解决的 https://youtrack.jetbrains.com/issue/KT-37425
