### ISSUE TITLE
老哥，咨询下跟网络请求无关的，请问demo里这个侧滑栏有时候拉不出来怎么办？有什么解决办法吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Net#55]
![微信图片_20220108122101](https://user-images.githubusercontent.com/54784104/148631196-55974712-cb20-4d3d-a1a9-4c5deb5523c4.jpg)

**Comment by liangjingkanji** [comment]
现在Android手机流行侧滑返回手势, 所以容易产生冲突. 主要看你手机系统优化如何了, demo用的是官方组件实现的侧滑菜单.

滑不动你就点击左上角菜单图标

**Comment by SaltedFish-Extreme** [comment]
> 现在Android手机流行侧滑返回手势, 所以容易产生冲突. 主要看你手机系统优化如何了, demo用的是官方组件实现的侧滑菜单.
> 
> 滑不动你就点击左上角菜单图标

啊，我还用的一加五，没有这个，感觉是DrawerLayout抽屉视图的问题🤔

**Comment by liangjingkanji** [comment]
在我的手机上侧滑压根没反应, 都是返回上一页

**Comment by liangjingkanji** [comment]
你以后写项目也别写侧滑菜单什么的, 不符合现在android交互了, 问题很多

**Comment by SaltedFish-Extreme** [comment]
> 在我的手机上侧滑压根没反应, 都是返回上一页

好吧，麻烦你了😂

**Comment by liangjingkanji** [comment]
说麻烦就见外了. 有空你把bug多改一改吧 
![image](https://user-images.githubusercontent.com/21078112/148632502-6c870117-55ff-4e9f-b1d5-449a36b4aabd.png)

**Comment by SaltedFish-Extreme** [comment]
> 说麻烦就见外了. 有空你把bug多改一改吧 ![image](https://user-images.githubusercontent.com/21078112/148632502-6c870117-55ff-4e9f-b1d5-449a36b4aabd.png)

好的😂
