### ISSUE TITLE
老哥，你这网络请求文档我咋看不明白呢😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Net#59]
我想请求玩安卓的接口，一开始没想到还要配置解析器，发现解析数据异常吐司才回头又看了遍文档，然后配置SerializationConverter解析时候有爆红的，又对比看了看demo才发现还要导入它的依赖
![微信图片_20220108151632](https://user-images.githubusercontent.com/54784104/148635833-da3480bd-48a2-41b0-8c7f-0ee01091b66e.png)
配置完了之后看文档可以在全局配置，但是不知道是在application里配置还是在哪，在application里的onCreate里面这样配置了还是解析数据异常
````kotlin
NetConfig.init("https://www.wanandroid.com/") {
            setConverter(SerializationConverter())
        }
````
![image](https://user-images.githubusercontent.com/54784104/148635748-2f72ae60-996d-4aa1-9605-43903683d6d0.png)
还有你的demo也出这个问题了😂
![微信图片_20220108151627](https://user-images.githubusercontent.com/54784104/148635952-8f7c9743-f2f9-4927-ba82-22c8fc93680b.jpg)

**Comment by SaltedFish-Extreme** [comment]
我仔细看了看，玩安卓的错误码是0为成功，是INT类型的，继承的JSONConvert错误码是字符串的，不知道是不是这个问题，但是我刚才自定义了SerializationConverter也不管用😢

**Comment by SaltedFish-Extreme** [comment]
我日，我把SerializationConverter换成GsonConvert就好了，不该字符串错误码和全局配置解析的事，一开始换成gson解析时用了retrofit相关的依赖，怪不得用gson也不行，老哥能把解析相关的依赖写的显明些吗😂话说kotlin那个解析可能有问题，有点坑😢

**Comment by liangjingkanji** [comment]
Gson要什么retrofit依赖

转换器分为单例和全局, 全局推荐在Application赋值. 单例就是针对每个请求赋值

错误码是Int不影响你使用JSONObject.getString()

**Comment by liangjingkanji** [comment]
转换器代码很简单, 你可以尝试读下转换器内部在做什么. 不然遇到业务和常规不符的需求你就不知道如何自定义转换器了.

**Comment by liangjingkanji** [comment]
另外假设你使用Net出现任何异常提示. 可以直接打开LogCat看错误信息. 不用到处猜

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 嗯，我一开始以为gson是依赖的com.squareup.retrofit2:converter-gson，最后全局搜你demo里关于gson的依赖才找到谷歌的，我原来一直和retrofit一起用的😂自定义的转换器大概看懂了一些，好像kotlin这个Serialization的解析有问题，你demo里也出问题了，Net打印的log一直都是类型转换异常，都在依赖的转换器里，我看不明白😢

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 话说老哥，刚才我加群也没有同意，进不去吗🤔
