### ISSUE TITLE
想问下作者，这个框架对于发出的同一个接口请求，多次刷新请求数据时，是否能终止上次请求执行新的发出请求呢？一般是怎么操作才合理呢？

### ISSUE THREAD

**Issue by LJYq** [liangjingkanji/Net#6]
想问下作者，这个框架对于发出的同一个接口请求，多次刷新请求数据时，是否能终止上次请求执行新的发出请求呢？一般是怎么操作才合理呢？

**Comment by liangjingkanji** [comment]
Net做这个很简单,  我直接给你写个Demo,  稍等

**Comment by liangjingkanji** [comment]
请查看Demo的左侧菜单的 "唯一请求",   文档对应左侧菜单的 "唯一请求"
