### ISSUE TITLE
全局设置中setRequestInterceptor里面覆盖Header失败

### ISSUE THREAD

**Issue by 4happymeatball** [liangjingkanji/Net#61]
![image](https://user-images.githubusercontent.com/8392173/148903038-0bba1daf-572e-467f-b976-097f2e2f138f.png)

Post请求，空body
设置之后Content-Type仍旧是application/x-www-form-urlencoded
目前采取的方法是参数里额外写一句json()

**Comment by liangjingkanji** [comment]
为什么要添加这个`application/x-www-form-urlencoded`

默认情况下就是表单参数, 你全局修改该参数会导致很多问题发生比如下载文件

`空body`你是在转化器里面确认的吗? 如果只是Post函数没有返回内容不一定. 因为转换器可以完全控制所有数据返回空

**Comment by liangjingkanji** [comment]
回复比较慢见谅

**Comment by 4happymeatball** [comment]
前后端对接的时候经常有很多奇葩情况，这个想必大家都被折磨过了，也不用多谈
比如现在的问题就是POST请求，但参数非要按在QueryParam里，body反而是空的
我的尝试是如果拿个拦截器把请求扣住，header里Content-Type改了再发就行了，但是单独为此写个拦截器觉得不值，看了眼文档有这个轻量的拦截器就决定试一下
但是最后发现并不能覆盖

**Comment by liangjingkanji** [comment]
因为OkHttp最终会再修改一次Content-Type. 所以只能写OkHttp的拦截器

**Comment by 4happymeatball** [comment]
了解了，那我研究自定义个body看看

**Comment by liangjingkanji** [comment]
说起来`json()`比`param()`强大的多, 你为什么一定要和param一样.....

```kotlin
json(
"name" to "MY_NAME",
"age" to "111"
)
```
`json()`支持Pair/Map/JSONObject/String

**Comment by 4happymeatball** [comment]
这不是后端不支持吗（捂脸）
我要是能让他改接口，我至于这么麻烦吗……

**Comment by liangjingkanji** [comment]
我看了下你的问题
`现在的问题就是POST请求，但参数非要按在QueryParam里，body反而是空的`

你使用`setQuery()`函数不就可以了. 这个和使用Post/Get没影响
