### ISSUE TITLE
强东哥，我想请求的url要动态拼接页码参数应该咋办？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Net#62]
比如请求玩安卓的分页数据列表，https://www.wanandroid.com/article/list/1/json
这个1应该怎样传过去，使用brv的上拉加载更多应该怎样拼接，我看文档和demo好像没有这部分😢

**Comment by liangjingkanji** [comment]
这不就是拼接字符串
```kotlin
binding.page.onRefresh {
  scope {
    Post<String>("https://www.wanandroid.com/article/list/${index}/json").await()
  }
}.showLoading()
```

**Comment by SaltedFish-Extreme** [comment]
> ```kotlin
>     Post<String>("https://www.wanandroid.com/article/list/${index}/json").await()
> ```
老哥，这样的话，这个url就没法提取出来做为常量统一管理了吧，我本来还打算提取出来当作常量用😂

**Comment by liangjingkanji** [comment]
提取url你提取分页干嘛, 你可以只提取
```
https://www.wanandroid.com/article/list
```
而且在url上拼接分页字段属于网页常用的, wanandroid的api设计不符合规范罢了

通过函数添加和你通过字符串拼接没有区别

**Comment by SaltedFish-Extreme** [comment]
> ```
> https://www.wanandroid.com/article/list
> ```
好的😂
