### ISSUE TITLE
异常处理必须要用try-catch的方式吗？

### ISSUE THREAD

**Issue by rayzeng0221** [liangjingkanji/Net#64]
不能像  rxjava一样  直接在中括号处理异常吗？

**Comment by liangjingkanji** [comment]
rxJava支持中括号处理异常? 中括号符号是`[]`, 你确定说的不是大括号`{}`
rxJava并没有错误处理机制, 只是有个错误回调或者使用`catch`操作符

Net异常处理可以分为两类
1. 捕获作用域内的协程
2. 捕获整个作用域异常(其中分为单例和全局错误处理)

具体可以看文档: [错误处理](https://liangjingkanji.github.io/Net/error-handle/#_2)
