### ISSUE TITLE
错误提示toast 内存泄漏

### ISSUE THREAD

**Issue by lisper-ip** [liangjingkanji/Net#65]
====================================
    HEAP ANALYSIS RESULT
    ====================================
    1 APPLICATION LEAKS
    
    References underlined with "~~~" are likely causes.
    Learn more at https://squ.re/leaks.
    
    58888 bytes retained by leaking objects
    Signature: 9f79c7a09d09e0075b068958c1330dabc98644dd
    ┬───
    │ GC Root: Thread object
    │
    ├─ android.os.HandlerThread instance
    │    Leaking: NO (PathClassLoader↓ is not leaking)
    │    Thread name: 'LeakCanary-Heap-Dump'
    │    ↓ Thread.contextClassLoader
    ├─ dalvik.system.PathClassLoader instance
    │    Leaking: NO (TipUtils↓ is not leaking and A ClassLoader is never leaking)
    │    ↓ ClassLoader.runtimeInternalObjects
    ├─ java.lang.Object[] array
    │    Leaking: NO (TipUtils↓ is not leaking)
    │    ↓ Object[88]
    ├─ com.drake.net.utils.TipUtils class
    │    Leaking: NO (a class is never leaking)
    │    ↓ static TipUtils.toast
    │                      ~~~~~
    ├─ android.widget.Toast instance
    │    Leaking: YES (This toast is done showing (Toast.mTN.mWM != null && Toast.mTN.mView == null))
    │    Retaining 58.9 kB in 59 objects
    │    mContext instance of android.app.Application
    │    ↓ Toast.mNextView
    ╰→ android.widget.LinearLayout instance
    ​     Leaking: YES (ObjectWatcher was watching this because android.widget.LinearLayout received
    ​     View#onDetachedFromWindow() callback)
    ​     Retaining 58.9 kB in 58 objects
    ​     key = 2e8d0274-e65f-4cb4-bb28-a4948228f6b0
    ​     watchDurationMillis = 11917
    ​     retainedDurationMillis = 6913
    ​     View not part of a window view hierarchy
    ​     View.mAttachInfo is null (view detached)
    ​     View.mID = R.id.null
    ​     View.mWindowAttachCount = 1
    ​     mContext instance of android.app.Application
    ====================================
    0 LIBRARY LEAKS

**Comment by lisper-ip** [comment]
代码  TipUtils.toast("异常")

**Comment by lisper-ip** [comment]
ToolTip也有同样的问题。直接运行的demo

**Comment by liangjingkanji** [comment]
长期持有Toast引用是为了避免Toast重复显示一直覆盖. 该内存泄漏可以忽略不计

**Comment by lisper-ip** [comment]
好的
