### ISSUE TITLE
POST 请求会发生 Caused by: java.lang.IllegalStateException: closed 这样的错误

### ISSUE THREAD

**Issue by masite** [liangjingkanji/Net#66]
版本：
api "com.squareup.okhttp3:okhttp:4.9.1"
    // Net
api 'com.github.liangjingkanji:Net:3.0.13'

场景：
get请求正常，用post请求时发生错误

错误信息：
com.drake.net.interceptor.NetOkHttpInterceptor.intercept(NetOkHttpInterceptor.kt:43)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
com.drake.net.interceptor.LogRecordInterceptor.intercept(LogRecordInterceptor.kt:53)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
com.component.myapplication.ui.login.LoginActivity$getSmsCode$1$invokeSuspend$$inlined$Post$default$1.invokeSuspend(NetCoroutine.kt:148)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

**Caused by: java.lang.IllegalStateException: closed**

业务代码：
初始化：
 NetConfig.init(baseUrl) {
            setLog(true) // LogCat异常日志
            addInterceptor(LogRecordInterceptor(true)) // 添加日志记录器
            this.setConverter(FastJsonConverter())
            setRequestInterceptor(object : RequestInterceptor {
                override fun interceptor(request: BaseRequest) {
                    request.addHeader("Authorization", "bearer ${SPUtils.getInstance().getString("token", "")}")
                    request.addHeader("Accept", "application/json")
                    request.addHeader("X-Requested-With", "XMLHttpRequest")

请求代码：
Post<WbgResponse<SmsCodeBean>>("acquire-sms") {
                    json(GsonUtils.toJson(map))
                    this.mediaType = JSON
                }.await()

其他：百度说是多次调用 response.body.string() 可是并没有呀0.0

请大佬帮忙分析一下咋回事

**Comment by liangjingkanji** [comment]
换个路径请求还是如此吗?

```
this.mediaType = JSON // 这行代码是多余, json()函数默认使用application/json
```

**Comment by masite** [comment]
模拟器会出问题，真机没问题。0.0 ，白忙活大半天
应该不是问题，对不起，打扰了

**Comment by liangjingkanji** [comment]
模拟器应该也不至于有问题吧
