### ISSUE TITLE
强东哥，这个怎么获取cookie😂我想用这个获取之后再用Serialize持久化，但是没找到类似的文章，都是用PersistentCookieStore和sp来做的，我都不知道cookieJar怎么来的，还没在客户端用过cookie😥

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Net#67]

**Comment by liangjingkanji** [comment]
你去百度okhttp获取cookie吧
客户端基本上不用cookie

**Comment by SaltedFish-Extreme** [comment]
> 你去百度okhttp获取cookie吧 客户端基本上不用cookie

好的😂我原来也没用过cookie，写玩安卓这个项目才看到还有cookie的😅

**Comment by liangjingkanji** [comment]
玩安卓就是个网页api. 写的不咋地

**Comment by SaltedFish-Extreme** [comment]
😂

**Comment by liangjingkanji** [comment]
Net牛逼就在完全兼容OkHttp功能. 有不会的需求直接搜索 OkHttp如何实现

**Comment by SaltedFish-Extreme** [comment]
> Net牛逼就在完全兼容OkHttp功能. 有不会的需求直接搜索 OkHttp如何实现

好的，谢谢老哥了😄

**Comment by liangjingkanji** [comment]
已经新增[Cookie管理](https://liangjingkanji.github.io/Net/cookie/)
