### ISSUE TITLE
如何处理客户端token刷新机制

### ISSUE THREAD

**Issue by weizhizhu** [liangjingkanji/Net#70]
场景需求：
1、有些api的调用是基于一个token，而这个token是会有效期限制的
2、基于第一点我想做一个基础的抽象函数的封装，就是在调用所有的api的时候判断或者等待这个token的刷新
3、能单独的不在scopeLife中直接创建Post然后返回在其他地方直接await()，这样我就可以比较好的去控制之后的流程

我不知道这样对不对，如果可以，我需要怎么做，如果不对，有没有比较好的建议

**Comment by liangjingkanji** [comment]
网络请求拦截器是来处理相关需求(使用文档第一章我就提到基本上业务不存在需要你封装请求动作). 根据token失效机制来处理
- 如果token失效是根据后端返回401状态码等决定, 那么创建`Interceptor`拦截器, 在拦截器中使用同步请求来先刷新token
- 如果token失效本地就可以根据时间计算失效, 那么创建`RequestInterceptor`请求拦截器更方便, 在拦截器中使用同步请求来先刷新token

[拦截器使用文档](https://liangjingkanji.github.io/Net/interceptor/), 如果对于拦截器有疑问可以谷歌搜索`OkHttp拦截器使用`

**Comment by weizhizhu** [comment]
感谢 我用拦截器初步实现了

**Comment by liangjingkanji** [comment]
以后基于全局参数/日志/参数加密/解密请都优先考虑拦截器
