### ISSUE TITLE
网络框架是否考虑用flow做协程的请求

### ISSUE THREAD

**Issue by qq570026938** [liangjingkanji/Net#72]
这样可以使用flow自带的一些map,filter等函数链式的处理一些数据在返回处理后的结果是不是更好些呢

**Comment by liangjingkanji** [comment]
首先kotlin集合本身就自带你说的`stream`函数, 并且比flow更多. 不存在什么flow能做的同步请求代码不能实现的

其次flow属于`回调请求`, Net2.0就是使用的rxJava实现的(flow属于和rxJava同一个类型). 回调请求使用复杂也无法快速写出并发请求, 代码也不够直观.

你这提议相当于让我`返祖`

**Comment by qq570026938** [comment]
> 首先kotlin集合本身就自带你说的`stream`函数, 并且比flow更多. 不存在什么flow能做的同步请求代码不能实现的
> 
> 其次flow属于`回调请求`, Net2.0就是使用的rxJava实现的(flow属于和rxJava同一个类型). 回调请求使用复杂也无法快速写出并发请求, 代码也不够直观.
> 
> 你这提议相当于让我`返祖`

额，好吧，另外问个问题，就是自动缺省页和自动分页能同时嵌套使用吗

**Comment by liangjingkanji** [comment]
示例代码

```
val result = Post<List<Data>>("api").await().map{ it.name }.filter{ name.contains("liu") }
```

**Comment by liangjingkanji** [comment]
> > 首先kotlin集合本身就自带你说的`stream`函数, 并且比flow更多. 不存在什么flow能做的同步请求代码不能实现的
> > 其次flow属于`回调请求`, Net2.0就是使用的rxJava实现的(flow属于和rxJava同一个类型). 回调请求使用复杂也无法快速写出并发请求, 代码也不够直观.
> > 你这提议相当于让我`返祖`
> 
> 额，好吧，另外问个问题，就是自动缺省页和自动分页能同时嵌套使用吗

你这个问题单独开issues详细描述吧, 我不是很理解
