### ISSUE TITLE
支持网络缓存吗

### ISSUE THREAD

**Issue by zhjun2016** [liangjingkanji/Net#73]

**Comment by liangjingkanji** [comment]
暂时是只支持OkHttp的缓存模式, 即只支持缓存GET请求. 其他缓存需要自己处理
不过目前正在加入强制缓存模式

**Comment by liangjingkanji** [comment]
目前已实现: [强制缓存](https://liangjingkanji.github.io/Net/cache/)和缓存+网络双重加载
