### ISSUE TITLE
能否拦截onError错误，手动创建指定对象返回，而不是抛出异常

### ISSUE THREAD

**Issue by tanranran** [liangjingkanji/Net#74]
var data=Get<BaseResult<UserModel>>("list").await()

比如，当无网络时，想手动返回一个BaseResult() 对象，而不是抛出异常

这么做的目的是想

if else（baseresult.code） 来判断所有业务异常+其它各种异常

**Comment by liangjingkanji** [comment]
异常请自定义异常对象去处理

如果需要任何数据可以用异常对象携带

**Comment by tanranran** [comment]
感谢大佬，目前看来只能通过Interceptor来实现了
