### ISSUE TITLE
在集成1.x的时候post和get、

### ISSUE THREAD

**Issue by a1227308812** [liangjingkanji/Net#75]
在1.x的使用中按照文档集成在kotlin'项目中在请求网络的时候直接报错编译不通过怎么回事呢

**Comment by a1227308812** [comment]
直接报错提示这个Cannot access class 'io.reactivex.Observable'. Check your module classpath for missing or conflicting dependencies

**Comment by a1227308812** [comment]
添加@Suppress("MISSING_DEPENDENCY_CLASS")忽略报错提示后
在编译时就报错这个：Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.drake.net.observer.TryObserver, unresolved supertypes: io.reactivex.Observer, io.reactivex.disposables.Disposable
Adding -Xextended-compiler-checks argument might provide additional information.

**Comment by liangjingkanji** [comment]
因为你没有依赖RxJava吧

> 不是很推荐你使用1.x版本, 建议用3.x

**Comment by a1227308812** [comment]
感谢回复，已处理。这几天在忙其他的没来得及及时回复。

**Comment by liangjingkanji** [comment]
好的
