### ISSUE TITLE
使用Coil指定callFactory为NetConfig.okHttpClient加载网络图片崩溃问题

### ISSUE THREAD

**Issue by lexdev7** [liangjingkanji/Net#76]
![3b6cb6c20a306314ada6ea50533358a](https://user-images.githubusercontent.com/31149744/162654181-5e06e2d5-26aa-4b5a-9566-9a9f2985622d.png)

**Comment by liangjingkanji** [comment]
Net是什么版本

**Comment by lexdev7** [comment]
Net:3.2.0
okhttp:4.9.1
在debug下未开混淆

**Comment by liangjingkanji** [comment]
然后你debug下也崩溃?

**Comment by lexdev7** [comment]
是的

**Comment by liangjingkanji** [comment]
你这个用法比较出奇. 由于你没有这个okHttpClient直接给Coil使用导致数据为空, 其反射字段获取失败

我会马上修复这个问题

**Comment by lexdev7** [comment]
好的，东哥辛苦了

**Comment by liangjingkanji** [comment]
试试这个版本
```groovy
implementation 'com.github.liangjingkanji:Net:24bac34493'
```

**Comment by lexdev7** [comment]
这个版本可以的，东哥

**Comment by liangjingkanji** [comment]
那你多用一会对接完Coil吧, 下午我发布个修复版本

**Comment by lexdev7** [comment]
好的

**Comment by liangjingkanji** [comment]
你是不是因为coil没有提供下载监听器, 所以打算用Net的下载进度监听器

**Comment by lexdev7** [comment]
是的，同时也是为了复用okhttpClient
