### ISSUE TITLE
文件下载校验问题

### ISSUE THREAD

**Issue by woaimi520** [liangjingkanji/Net#78]
下载是否开启MD5校验, 如果服务器返回 "Content-MD5"响应头和制定路径已经存在的文件MD5相同是否直接返回File, 不会重新下载

我发现 NetConverter的 onConvert 都是在完全下载完成后才会调用,也就是如下判断都在完全下载后进行,这里是否和接口说明有矛盾,或是我没找到正确方式?
```kotlin
if (request.downloadMd5Verify()) {
    val md5Header = request.header("Content-MD5")
    if (file.md5() == md5Header) return file
}
```

**Comment by woaimi520** [comment]
我是如下的方式添加的,我实际调试,看到是从进度监听中看到数据是完全下载 也就是打印到了100% 才会走到自定义的 converter中去的,现象看上去就是下载完成后才判断md5的
       scopeNetLife {

           Get<File>(downloadUrl) {
               setDownloadFileName(fileName)
               setDownloadDir(filePath)
               log("下载地址Url: $downloadUrl ")
               log("下载地址存储: $filePath ")

               addDownloadListener(object : ProgressListener() {
                   override fun onProgress(p: Progress) {
                       val progress = p.progress()
                       log("下载进度: $progress% 下载速度: ${p.speedSize()}     " +
                               "\n\n文件大小: ${p.totalSize()}  已下载: ${p.currentSize()}  剩余大小: ${p.remainSize()}" +
                               "\n\n已使用时间: ${p.useTime()}  剩余时间: ${p.remainTime()}")
                       GlobalScope.launch {
                           withContext(Dispatchers.Main) {
                               downloadLiveData.value = progress.toInt()
                           }
                       }
                   }
               })

               if(isCheckMD5){
                   setDownloadMd5Verify()
               }else{}
               converter = NetConverterMd5()
           }.await().install()

       }

因为服务端返回的字段不是默认的response.file中 我替换了成了headers.get("full-file-md5")中的
class NetConverterMd5 : NetConverter {
    override fun <R> onConvert(succeed: Type, response: Response): R? {
        return when {
            succeed === String::class.java -> response.body?.string() as R
            succeed === ByteString::class.java -> response.body?.byteString() as R
            succeed.toString().contentEquals("byte[]") -> response.body?.bytes() as R
            succeed === Response::class.java -> response as R
            /** 改用对应服务端的 字段 */
            succeed === File::class.java -> response.fileMd5() as R
            else -> throw ConvertException(response, "An exception occurred while converting the NetConverter.DEFAULT")
        }
    }
}

/**
 * 下载到指定文件
 */
@Throws(DownloadFileException::class)
fun Response.fileMd5(): File? {
    val downloadDir = request.downloadFileDir()
    val fileName = fileName()
    var file = File(downloadDir, fileName)
    try {
        if (file.exists()) {
            // MD5校验匹配文件
            if (request.downloadMd5Verify()) {
                val md5Header = headers.get("full-file-md5")
                //headers.get("full-file-md5")
                if (file.md5() == md5Header) return file
            }
            // 命名冲突添加序列数字的后缀
            if (request.downloadConflictRename() && file.name == fileName) {
                val fileExtension = file.extension
                val fileNameWithoutExtension = file.nameWithoutExtension
                fun rename(index: Long): File {
                    file = File(downloadDir, fileNameWithoutExtension + "_($index)" + fileExtension)
                    return if (file.exists()) {
                        rename(index + 1)
                    } else file
                }
                file = rename(1)
            }
        }

        // 临时文件
        if (request.downloadTempFile()) {
            file = File(downloadDir, file.name + ".net-download")
        }
        val source = body?.source() ?: return null
        if (!file.exists()) file.createNewFile()
        file.sink().buffer().use {
            it.writeAll(source)
        }
        // 下载完毕删除临时文件
        if (request.downloadTempFile()) {
            val fileFinal = File(downloadDir, fileName)
            file.renameTo(fileFinal)
            return fileFinal
        }
        return file
    } catch (e: SocketException) {
        // 取消请求需要删除下载临时文件
        if (request.downloadTempFile()) file.delete()
        throw CancellationException(e)
    } catch (e: Exception) {
        throw DownloadFileException(this, cause = e)
    }
}

**Comment by woaimi520** [comment]
已经包裹了 主要就是 我是在收到了进度回调后 才看到md5的条件判断,主要是app比较大 我会等很久才看走到判断那里  感觉是进行了下载了

**Comment by woaimi520** [comment]
这里 是使用 converter = NetConverterMd5() 来替换规则的吗?我确实匹配成功了 但是从日志时间可以看出进度监听先返回的 然后才走到md5 校验, 如果可以能否提供下demo 感谢大佬
```
 // MD5校验匹配文件
            if (request.downloadMd5Verify()) {
                val md5Header = headers.get("full-file-md5")
                //headers.get("full-file-md5")
                if (file.md5() == md5Header) return file
            }
```

这段确实已经执行了 但是 都是在回调进度监听之后

```
2022-04-12 18:25:39.754 30481-31515/? D/TAG_DEFAULT:  
    │ DefaultDispatcher-worker-1, com.changan.moblie.casdkbase.utils.log.LogUtils$Companion.fileD$default(LogUtils.kt:500)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ 下载进度: 4% 下载速度: 3.18 MB     
    │ 
    │ 文件大小: 161 MB  已下载: 6.92 MB  剩余大小: 154 MB
    │ 
    │ 已使用时间: 00:02  剩余时间: 00:48
    └────────────────────────────────────────────────────
```
```
2022-04-12 18:26:50.854 30481-31515/? D/TAG_DEFAULT:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ DefaultDispatcher-worker-1, com.changan.moblie.casdkbase.utils.log.LogUtils$Companion.fileD$default(LogUtils.kt:500)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ md5 值匹配 返回file
```

**Comment by liangjingkanji** [comment]
为避免版本太旧导致问题, 你先升级到最新版本吧

**Comment by liangjingkanji** [comment]
你可以fork当前仓库复现问题(是你提供产生问题的demo而不是我提供正常demo给你看), 不然我无法复现问题我也无法解决问题

比如以下修改可以每次模拟服务器返回MD5匹配值
```kotlin
if (file.md5() =="固定文件MD5值")
//...
```
至于即返回File又会执行下载进度监听, 我认为是不可能出现的情况.

**Comment by woaimi520** [comment]
升级到最新版本也会先在 addDownloadListener 添加的监听中收到回调, 打印到100%后 才会走到 converter 中的onConvert回调中去,

**Comment by liangjingkanji** [comment]
没有demo吗?

**Comment by liangjingkanji** [comment]
不能fork仓库复现问题吗?

**Comment by liangjingkanji** [comment]
你可以试试新的缓存模式, 可以直接缓存任何数据包括文件, 无网络情况下都可以
