### ISSUE TITLE
dialogscope lifecycle 我看有的只有add ondestroyevent的时候不移除嘛

### ISSUE THREAD

**Issue by ccccmmmz** [liangjingkanji/Net#79]

**Comment by liangjingkanji** [comment]
你的标题和问题描述稍微清楚一点, 不是很能理解你的意思

**Comment by ccccmmmz** [comment]
就是你看dialogScope这个类中只有addLifeCycleObservaber 没有remove

**Comment by liangjingkanji** [comment]
有引发内存泄漏吗? [官方解释是不需要remove](https://github.com/googlecodelabs/android-lifecycles/issues/5)

**Comment by ccccmmmz** [comment]
get了 网络请求过程中限速有没有好的思路啊

**Comment by liangjingkanji** [comment]
没遇到过这种需求不好意思, 如果是下载限速你可以控制读取的缓存大小

**Comment by ccccmmmz** [comment]
好吧 大佬加油 周天还这么肝

**Comment by liangjingkanji** [comment]
我在更新强制缓存模式

**Comment by ccccmmmz** [comment]
有其他项目带带弟弟

**Comment by liangjingkanji** [comment]
那就这个Net你pr吧
