### ISSUE TITLE
Fragment.scopeLife默认销毁生命周期错误

### ISSUE THREAD

**Issue by lexdev7** [liangjingkanji/Net#80]
![053b434fb3bc2b5e36599a39a77d950](https://user-images.githubusercontent.com/31149744/165703494-b85aea18-eff4-4bf7-a57c-0f33f2645e21.png)

**Comment by liangjingkanji** [comment]
我感觉是写错了, 被你抓到了

既然是你抓到的, 如果你有想法的话可以[发起pr](https://liangjingkanji.github.io/document/)

**Comment by lexdev7** [comment]
哈哈，我来试试

**Comment by liangjingkanji** [comment]
提醒下提交使用自己GitHub账号邮箱自己的头像才会出现在**Contributors**

**Comment by lexdev7** [comment]
我觉得应该改为Lifecycle.Event.ON_DESTROY，这样是否合理

**Comment by liangjingkanji** [comment]
主要是Fragment很多并不会被销毁(onDestory)只是onDestroyView, 比如你使用navigation或者replace/show/hidden

**Comment by liangjingkanji** [comment]
关于这个问题稍后我会修复

**Comment by lexdev7** [comment]
好的，谢东哥

**Comment by liangjingkanji** [comment]
你这刚好提醒到我了, 你现在使用最新版本吧
