### ISSUE TITLE
java和kotlin的项目可以使用吗？ 还是只可以在kotlin 项目中使用？

### ISSUE THREAD

**Issue by ChenSiWu** [liangjingkanji/Net#82]
## 问题描述
java和kotlin的项目可以使用吗？ 还是只可以在kotlin 项目中使用？
### 期望行为
如果可以在java 代码中使用，能有个demo 吗

**Comment by liangjingkanji** [comment]
如果项目完全不存在kt就不推荐用了

**Comment by ChenSiWu** [comment]
x想

> 如果项目完全不存在kt就不用推荐了

有部分代码是kt 部分是java, 只有在kt的代码中才可以使用net吗

**Comment by liangjingkanji** [comment]
可以kt封装, java调用来解决

**Comment by ChenSiWu** [comment]
明白了。谢谢啊
