### ISSUE TITLE
SerializationConverter在demo中就出现解析错误

### ISSUE THREAD

**Issue by zkzk7749** [liangjingkanji/Net#83]
## 问题描述
SerializationConverter在demo中就出现解析错误
### 期望行为
修正一下demo
## 如何复现
现有的demo在SerializationConvertFragment中就直接提示解析错误
建议步骤:
- 是否可以在sample复现
- 是

**Comment by liangjingkanji** [comment]
建议拉取下仓库最新代码

**Comment by zkzk7749** [comment]
东哥有空的时候把demo的 gradle 升一下吧，现在都7.1以上了

**Comment by liangjingkanji** [comment]
不影响新版本AS运行，主要是怕旧版本无法编译所以没升级
