### ISSUE TITLE
图片下载失败问题

### ISSUE THREAD

**Issue by qq570026938** [liangjingkanji/Net#84]
## 问题描述
这个图片地址，在浏览器上直接输入可以下载，用postman请求也能请求通过，但是用Net请求出现403问题
https://kaola-app.oss.kaolacdn.com/20220504337466f99d1b4a0d8c65d3c2d57d0e9a.jpg
### 期望行为
希望可以解决一下，为什么会出现这种情况呢
## 如何复现
下载文件时使用上面的地址即可复现

## 版本
- Net: 3.4.6
- OkHttp:  5.0.0-alpha.2

**Comment by liangjingkanji** [comment]
403按照Http规范这是被服务器禁止访问了, 你手机和电脑不在同一网络, 电脑在白名单但是手机网络不在

**Comment by qq570026938** [comment]
> 403按照Http规范这是被服务器禁止访问了, 估计是你手机和电脑不在同一网络, 电脑在白名单但是手机网络不在

我明白了，谢谢，我发现这个地址其实还有个问题就是手机请求还要模拟个UA,刚刚发现的问题

**Comment by liangjingkanji** [comment]
好的, 我会重新编辑把你发的地址删除
