### ISSUE TITLE
取消请求

### ISSUE THREAD

**Issue by hanyechun** [liangjingkanji/Net#85]
你好：
我看到Net使用文档里写着取消请求方式用uid
Get<String>("api", uid = "请求用户信息").await()
但是我发现GET、POST中没有uid这个参数，我在上传、下载监听
DownloadListener(id: Any, progressListener: ProgressListener)
找到了请求ID，Net.cancelId(id)
是不是只有上传、下载监听才提供了cancelId?
感谢。

**Comment by liangjingkanji** [comment]
文档错误我稍后修复

请参考以下示例, `{}`支持所有请求配置
```kotlin
scopeNetLife {
    binding.tvFragment.text = Get<String>("banner/json"){
        setId("请求用户信息")
    }.await()
}
```

**Comment by hanyechun** [comment]
好的，谢谢。

**Comment by liangjingkanji** [comment]
已经修复文档
