### ISSUE TITLE
缓存KEY可以通过拦截器统一设置吗

### ISSUE THREAD

**Issue by kingyangcn** [liangjingkanji/Net#90]
## 问题描述
想通过拦截器统一设置自定义缓存KEY

**Comment by liangjingkanji** [comment]
当然可以, 请查看文档[拦截器](https://liangjingkanji.github.io/Net/interceptor/)

**Comment by kingyangcn** [comment]
@liangjingkanji 设置了强制缓存模式，不设置缓存有效期默认是永久吗？这种情况下是否能根据HTTP缓存协议设置有效期呢？

**Comment by liangjingkanji** [comment]
1. 所有缓存都优先遵守LRU原则(`最近最少使用`)
2. 设置强制缓存不影响标准Http缓存协议遵守协议

**Comment by kingyangcn** [comment]
> 1. 所有缓存都优先遵守LRU原则(`最近最少使用`)
> 2. 一个接口存在Http缓存协议且同时为其设置强制缓存模式, 这时会无视Http缓存协议

由于我们接口全部使用post加密传输，想问下是否能够实现强制post使用http缓存有效期？

**Comment by liangjingkanji** [comment]
文档中就是使用的Post, 支持任何请求方式缓存

**Comment by liangjingkanji** [comment]
Http标准缓存协议不支持`POST`

**Comment by kingyangcn** [comment]
@liangjingkanji 我的意思是强制post使用缓存的同时，缓存有效期仍然由服务器端通过Cache-Control控制

**Comment by liangjingkanji** [comment]
这种奇葩需求只能自己配置了
你可以在拦截器里面读取`Response.Header`然后设置强制缓存有效期
