### ISSUE TITLE
TabLayout+ViewPager2快速切换导致网络请求被取消

### ISSUE THREAD

**Issue by kingyangcn** [liangjingkanji/Net#91]
## 问题描述
```kotlin
state.onRefresh {
    scope {
        tvFragment.text = Get<String>("api").await()
    }
}.showLoading()
```
配合TabLayout+ViewPager2使用，网络请求还未返回数据时切换至其他Tab，网络请求会被取消导致没有数据。但是测试切换至其他Tab时发现Fragment并没有走onDestroyView，为什么网络请求会取消，请大佬赐教
### 期望行为
切换至其他Tab时网络请求不被取消

**Comment by liangjingkanji** [comment]
能否在fork仓库复现问题? 因为我无法复现你的问题

**Comment by kingyangcn** [comment]
> 能否在fork仓库复现问题? 因为我无法复现你的问题
### 复现视频
https://github.com/kingyangcn/Net/raw/master/1.mp4
### 复现代码
https://github.com/kingyangcn/Net

**Comment by liangjingkanji** [comment]
ViewPage2的确存在这个问题, 视图会触发`onViewDetachedFromWindow`

建议你暂时使用ViwPage替代, 等待这个问题修复或者欢迎提供PR

**Comment by liangjingkanji** [comment]
请替换以下版本检查是否还存在问题
```groovy
implementation 'com.github.liangjingkanji:Net:6e7dbf4b24'
```

**Comment by liangjingkanji** [comment]
你将BRV升级至1.3.76可以解决此问题

**Comment by kingyangcn** [comment]
> 你将BRV升级至1.3.76可以解决此问题, 这还是因为ViewPager2将视图`detach`导致`SmartRefreshLayout`的刷新状态异常...
> 
> 没有问题后我会发布Net正式版本

没问题了。另外想问下Q群为啥加不上，加了几次一直没人同意

**Comment by liangjingkanji** [comment]
应该不会吧, 你可以再试试, 也许你账号属于风险账号被过滤掉了

**Comment by kingyangcn** [comment]
> 应该不会吧, 你可以再试试, 也许你账号属于风险账号被过滤掉了

用小号尝试过也没加上。刚加了群，群主Q也加了，麻烦看下呢

**Comment by liangjingkanji** [comment]
你可以再多检查下其他页面网络请求取消是否正常，另外群主并不是我

**Comment by kingyangcn** [comment]
> 你可以再多检查下其他页面网络请求取消是否正常，另外群主并不是我

测了两个地方应该是没问题了。大佬能否给个联系方式，想跪舔一波

**Comment by liangjingkanji** [comment]
我只是一种互联网开源精神存续

**Comment by kingyangcn** [comment]
> 我只是一种互联网开源精神存续

好感动，感谢东哥

**Comment by liangjingkanji** [comment]
使用指定版本号吧
```groovy
implementation 'com.github.liangjingkanji:Net:3.4.9'
```
