### ISSUE TITLE
增加WebSocket的方法吧

### ISSUE THREAD

**Issue by Xiaolangs** [liangjingkanji/Net#93]
## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net:
- OkHttp: 
- Android:
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
OkHttp自带WebSocket

**Comment by liangjingkanji** [comment]
针对Android系统优化的WebSocket不适合出现在Http请求库中, 如果有空也许我会开源但是不会直接内嵌到本框架中(可能作为三方依赖)
