### ISSUE TITLE
请求报错，在postman或者网页上直接输入能请求成功

### ISSUE THREAD

**Issue by qq570026938** [liangjingkanji/Net#95]
## 问题描述
请求报错：com.drake.net.exception.HttpFailureException
### 期望行为
希望看一下为什么会这样

## 如何复现
请求下面地址：
http://*****

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)

## 版本
- Net: 3.4.10
- OkHttp: 5.0.0
- Android:12
- Gradle: 
- Android Studio:

**Comment by liangjingkanji** [comment]
希望你发出HttpFailureException包含的堆栈信息, 它包含具体错误信息

**Comment by liangjingkanji** [comment]
你使用标签过滤掉了, 请查看完整的错误堆栈信息而不是`OKPRFL_`

**Comment by liangjingkanji** [comment]
`HttpFailureException`错误代表属于客户端错误, 例如无网络

**Comment by qq570026938** [comment]
> 1. `HttpFailureException`该类表示Http请求在服务器响应之前失败, 例如无网络
> 2. `HttpResponseException`该类表示Http请求在服务器响应成功后失败

可以保证网络良好，换其他地址，访问正常，你说的日志这个快，我没有找到更多相关信息。。。

**Comment by liangjingkanji** [comment]
你使用`Net_LOG`来过滤日志或者查看当前应用的所有日志

**Comment by liangjingkanji** [comment]
看样子是你自定义输出错误信息, 但是只输出`message`导致没有堆栈信息了

<img width="566" alt="image" src="https://user-images.githubusercontent.com/21078112/176411777-1296f1e7-066a-44f8-b05f-7c1c0430ea43.png">

你看你都把TAG改成了"错误", 你应当保留堆栈信息来便于排查问题的

**Comment by qq570026938** [comment]
我是把请求的Get<String>().awit()代码try catch 了用的普通log打印的错误信息

**Comment by liangjingkanji** [comment]
请保留堆栈信息, 比如如下代码
```kotlin
Log.e("NET_TAG", "捕获错误", e)
```

**Comment by qq570026938** [comment]
这个是说我地址错误？

**Comment by liangjingkanji** [comment]
返回string那不就请求成功了?

**Comment by qq570026938** [comment]
不是，我意思是，我请求这个地址要返回个string,单结果是报这个错了，这个错是因为我请求地址有问题吗

**Comment by liangjingkanji** [comment]
有问题先用demo复现吧, 我没有多余精力或时间来猜测或者排查业务问题

**Comment by qq570026938** [comment]
> 有问题先用demo复现吧, 我没有多余精力或时间来猜测或者排查业务问题

好的，我在看看吧，谢谢

**Comment by liangjingkanji** [comment]
我建议你发生网络请求错误先用接口测试工具然后使用Net的demo来复现, 避免本地网络导致的问题影响你的判断

网络问题很多的, 甚至可能是OkHttp自身问题

**Comment by qq570026938** [comment]
应该就是库的问题了，我用Net.get()方法请求返回string正常，用Get().awit()返回字符串就不正常

**Comment by liangjingkanji** [comment]
希望你用OkHttp原始请求尝试一次

**Comment by qq570026938** [comment]
经过多次验证，发现是因为设置了两次user-agent的原因，在全局拦截设置了header 在请求的时候设置了专用的header,就出现这个地址请求失败的问题了，这个是什么原理，设置两次user-agent就无法访问

**Comment by qq570026938** [comment]
我看Net框架请求日志上是把两个user-agent拼接后请求的，如果拼接后是设置了一个user-agent的话应该是可以访问的，但实际上不能访问，是因为框架在请求的时候还是按照两个user-agent请求的吗，这个有解决方法吗

**Comment by liangjingkanji** [comment]
请求头可以通过addHeader拼接成求组是常识，你应该使用setHeader来覆盖

**Comment by qq570026938** [comment]
> 请求头可以通过addHeader拼接成求组是常识，你应该使用setHeader来覆盖

明白了，是我的问题，谢谢

**Comment by liangjingkanji** [comment]
希望你多自己仔细排查问题，我已经多次建议过fork复现问题了，而不是第一时间问我为什么，因为这个项目是开源的

**Comment by qq570026938** [comment]
好的，我会多看看的，这个问题看了好久没找出原因，，我还想问一下就是都用setHeader()，最后的请求会在拦截器里覆盖成全局的header,这个怎么处理呀

**Comment by liangjingkanji** [comment]
覆盖全局不就是应该的吗？我不太知道你要怎么处理

**Comment by qq570026938** [comment]
全局的header 不应该是处理成可以被单独的特定请求的header覆盖才好点吗，就像设置的全局baseUrl 可以被请求得完整得http://**地址覆盖一样

**Comment by liangjingkanji** [comment]
拦截器在请求之后，你先弄明白先后顺序，所有网络请求都如此，你可以自己添加标签去在拦截器判断

**Comment by qq570026938** [comment]
哦哦，明白了
