### ISSUE TITLE
Net最新版本取消了内置BubbleDialog 吗？

### ISSUE THREAD

**Issue by BatterMan-Li** [liangjingkanji/Net#96]
目前使用的是Net:3.4.6版本，为什么没有引用到BubbleDialog，请问是取消了吗？
![image](https://user-images.githubusercontent.com/28614345/176411541-30c80cea-5c61-4399-a2b2-b2a3300de3b7.png)

**Comment by liangjingkanji** [comment]
这个应该没自带过吧, 这是[Tooltip](https://github.com/liangjingkanji/Tooltip)框架的类

**Comment by BatterMan-Li** [comment]
OK
