### ISSUE TITLE
界面传值实体类序列化疑问咨询

### ISSUE THREAD

**Issue by BatterMan-Li** [liangjingkanji/Net#97]
Net和kotlin推荐的实体类使用kotlin Serializablez序列化，但是界面间传值putExtras中使用的序列化是java.io.Serializable, 请问界面间跳转传值应该如何使用或者有什么好的解决办法呢!

**Comment by liangjingkanji** [comment]
两者有互相影响吗?

**Comment by liangjingkanji** [comment]
`@Serializable`注解和`Serializable`接口只是同名罢了

**Comment by BatterMan-Li** [comment]
![image](https://user-images.githubusercontent.com/28614345/176607809-e40d3baf-fc12-4aba-b945-1a4d56e9b89e.png)
那我是不是两个序列化都实现呢！这样intent.putExtras也能使用

**Comment by liangjingkanji** [comment]
是的

**Comment by BatterMan-Li** [comment]
好的，谢谢你
