### ISSUE TITLE
Net缺失了Net.trace(url, function)函数

### ISSUE THREAD

**Issue by ZXHHYJ** [liangjingkanji/Net#99]
能否不固定appcompat的版本，项目默认导入了`  implementation 'androidx.appcompat:appcompat:1.3.1'`
同时，缺失了`Net.trace(url, function)`请求

**Comment by ZXHHYJ** [comment]
1.是的，我认为现在的项目默认都使用了AppCompat，这里的导入有些多余，同时现在Compose项目默认用的是`Activity-Compose`，使用Net容易额外导入了不需要的包
2.Good

**Comment by liangjingkanji** [comment]
`Activity-Compose`包含net所需包吗? 不会导致编译失败吧, 你可以fork仓库尝试是否有问题

因为目前没有正式为compose适配

**Comment by liangjingkanji** [comment]
你要使用Compose完全不使用compat库我觉得在正式项目中无法做到

**Comment by ZXHHYJ** [comment]
https://github.com/liangjingkanji/Net/pull/100
